<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;

class CreateWeapons extends Migration {

	/**
	 * Run the migrations.
	 *
	 * @return void
	 */
	public function up()
	{
		Schema::create('weapons', function(Blueprint $table)
		{
			$table->increments('weapon_id');
			$table->string('name')->unique();
			$table->string('category');
			$table->string('subcategory');
			$table->text('description')->nullable();
			$table->double('cost')->nullable();
			$table->string('dmg_small');
			$table->string('dmg_medium');
			$table->string('critical');
			$table->integer('range')->nullable();
			$table->double('weight_small')->nullable();
			$table->integer('weight_medium')->nullable();
			$table->string('type');
			$table->string('special');
		});

        DB::table('weapons')->insert(array(array(
            'name' => 'Gauntlet',
            'category' => 'Simple Weapons',
            'subcategory' => 'Unarmed Attacks',
            'description' => 'This metal glove lets you deal lethal damage rather than nonlethal damage with unarmed strikes. A strike with a gauntlet is otherwise considered an unarmed attack. The cost and weight given are for a single gauntlet. Medium and heavy armors (except breastplate) come with gauntlets. Your opponent cannot use a disarm action to disarm you of gauntlets.',
            'cost' => 2,
            'dmg_small' => '1d2',
            'dmg_medium' => '1d3',
            'critical' => 'x2',
            'range' => null,
            'weight_small' => 0.5,
            'weight_medium' => 1,
            'type' => 'B',
            'special' => '',
        ), array(
            'name' => 'Unarmed strike',
            'category' => 'Simple Weapons',
            'subcategory' => 'Unarmed Attacks',
            'description' => 'A Medium character deals 1d3 points of nonlethal damage with an unarmed strike. A Small character deals 1d2 points of nonlethal damage. A monk or any character with the Improved Unarmed Strike feat can deal lethal or nonlethal damage with unarmed strikes, at his discretion. The damage from an unarmed strike is considered weapon damage for the purposes of effects that give you a bonus on weapon damage rolls. An unarmed strike is always considered a light weapon. Therefore, you can use the Weapon Finesse feat to apply your Dexterity modifier instead of your Strength modifier to attack rolls with an unarmed strike. Unarmed strikes do not count as natural weapons (see Combat).',
            'cost' => 0,
            'dmg_small' => '1d2',
            'dmg_medium' => '1d3',
            'critical' => 'x2',
            'range' => null,
            'weight_small' => null,
            'weight_medium' => null,
            'type' => 'B',
            'special' => 'nonlethal',
        ), array(
            'name' => 'Dagger',
            'category' => 'Simple Weapons',
            'subcategory' => 'Light Melee Weapons',
            'description' => "A dagger has a blade that is about 1 foot in length. You get a +2 bonus on Sleight of Hand skill checks made to conceal a dagger on your body (see Using Skills).",
            'cost' => 2,
            'dmg_small' => '1d3',
            'dmg_medium' => '1d4',
            'critical' => '19-20 / x2',
            'range' => 10,
            'weight_small' => 0.5,
            'weight_medium' => 1,
            'type' => 'P or S',
            'special' => '',
        ), array(
            'name' => 'Punching Dagger',
            'category' => 'Simple Weapons',
            'subcategory' => 'Light Melee Weapons',
            'description' => "A punching dagger's blade is attached to a horizontal handle that projects out from the fist when held.",
            'cost' => 2,
            'dmg_small' => '1d3',
            'dmg_medium' => '1d4',
            'critical' => 'x3',
            'range' => null,
            'weight_small' => 0.5,
            'weight_medium' => 1,
            'type' => 'P',
            'special' => '',
        ), array(
            'name' => 'Spiked Gauntlet',
            'category' => 'Simple Weapons',
            'subcategory' => 'Light Melee Weapons',
            'description' => "The cost and weight given are for a single gauntlet. An attack with a spiked gauntlet is considered an armed attack. Your opponent cannot use a disarm action to disarm you of spiked gauntlets.",
            'cost' => 5,
            'dmg_small' => '1d3',
            'dmg_medium' => '1d4',
            'critical' => 'x2',
            'range' => null,
            'weight_small' => 0.5,
            'weight_medium' => 1,
            'type' => 'P',
            'special' => '',
        ), array(
            'name' => 'Light Mace',
            'category' => 'Simple Weapons',
            'subcategory' => 'Light Melee Weapons',
            'description' => "A mace is made up of an ornate metal head attached to a simple wooden or metal shaft.",
            'cost' => 5,
            'dmg_small' => '1d4',
            'dmg_medium' => '1d6',
            'critical' => 'x2',
            'range' => null,
            'weight_small' => 2,
            'weight_medium' => 4,
            'type' => 'B',
            'special' => '',
        ), array(
            'name' => 'Sickle',
            'category' => 'Simple Weapons',
            'subcategory' => 'Light Melee Weapons',
            'description' => "S sickle is a short, curved blade attached to a simple handle.",
            'cost' => 6,
            'dmg_small' => '1d4',
            'dmg_medium' => '1d6',
            'critical' => 'x2',
            'range' => null,
            'weight_small' => 1,
            'weight_medium' => 2,
            'type' => 'S',
            'special' => 'trip',
        ), array(
            'name' => 'Club',
            'category' => 'Simple Weapons',
            'subcategory' => 'One-Handed Melee Weapons',
            'description' => "A thick stick",
            'cost' => 0,
            'dmg_small' => '1d4',
            'dmg_medium' => '1d6',
            'critical' => 'x2',
            'range' => 10,
            'weight_small' => 1.5,
            'weight_medium' => 3,
            'type' => 'B',
            'special' => '',
        ), array(
            'name' => 'Heavy Mace',
            'category' => 'Simple Weapons',
            'subcategory' => 'One-Handed Melee Weapons',
            'description' => "A heavy mace has a larger head and a longer handle than a normal mace.",
            'cost' => 12,
            'dmg_small' => '1d6',
            'dmg_medium' => '1d8',
            'critical' => 'x2',
            'range' => null,
            'weight_small' => 4,
            'weight_medium' => 8,
            'type' => 'B',
            'special' => '',
        ), array(
            'name' => 'Morningstar',
            'category' => 'Simple Weapons',
            'subcategory' => 'One-Handed Melee Weapons',
            'description' => "A morningstar is a spiked metal ball, affixed to the top of a long handle.",
            'cost' => 8,
            'dmg_small' => '1d6',
            'dmg_medium' => '1d8',
            'critical' => 'x2',
            'range' => null,
            'weight_small' => 3,
            'weight_medium' => 6,
            'type' => 'B and P',
            'special' => '',
        ), array(
            'name' => 'Shortspear',
            'category' => 'Simple Weapons',
            'subcategory' => 'One-Handed Melee Weapons',
            'description' => "A shortspear is about 3 feet in length, making it a suitable thrown weapon.",
            'cost' => 1,
            'dmg_small' => '1d4',
            'dmg_medium' => '1d6',
            'critical' => 'x2',
            'range' => 20,
            'weight_small' => 1.5,
            'weight_medium' => 3,
            'type' => 'P',
            'special' => '',
        ), array(
            'name' => 'Longspear',
            'category' => 'Simple Weapons',
            'subcategory' => 'Two-Handed Melee Weapons',
            'description' => "A longspear is about 8 feet in length.",
            'cost' => 5,
            'dmg_small' => '1d6',
            'dmg_medium' => '1d8',
            'critical' => 'x3',
            'range' => null,
            'weight_small' => 4.5,
            'weight_medium' => 9,
            'type' => 'P',
            'special' => 'brace, reach',
        ), array(
            'name' => 'Quarterstaff',
            'category' => 'Simple Weapons',
            'subcategory' => 'Two-Handed Melee Weapons',
            'description' => "A quarterstaff is a simple piece of wood, about 5 feet in length.",
            'cost' => 0,
            'dmg_small' => '1d4/1d4',
            'dmg_medium' => '1d6/1d6',
            'critical' => 'x2',
            'range' => null,
            'weight_small' => 2,
            'weight_medium' => 4,
            'type' => 'B',
            'special' => 'double, monk',
        ), array(
            'name' => 'Spear',
            'category' => 'Simple Weapons',
            'subcategory' => 'Two-Handed Melee Weapons',
            'description' => "A spear is 5 feet in length and can be thrown.",
            'cost' => 2,
            'dmg_small' => '1d6',
            'dmg_medium' => '1d8',
            'critical' => 'x2',
            'range' => 20,
            'weight_small' => 3,
            'weight_medium' => 6,
            'type' => 'P',
            'special' => 'brace',
        ), array(
            'name' => 'Blowgun',
            'category' => 'Simple Weapons',
            'subcategory' => 'Ranged Weapons',
            'description' => "Blowguns are generally used to deliver debilitating (but rarely fatal) poisons from a distance. They are nearly silent when fired. For a list of appropriate poisons, see Poison.",
            'cost' => 2,
            'dmg_small' => '1',
            'dmg_medium' => '1d2',
            'critical' => 'x2',
            'range' => 20,
            'weight_small' => 0.5,
            'weight_medium' => 1,
            'type' => 'P',
            'special' => '',
        ), array(
            'name' => 'Heavy Crossbow',
            'category' => 'Simple Weapons',
            'subcategory' => 'Ranged Weapons',
            'description' => "You draw a heavy crossbow back by turning a small winch. Loading a heavy crossbow is a full-round action that provokes attacks of opportunity. Normally, operating a heavy crossbow requires two hands. However, you can shoot, but not load, a heavy crossbow with one hand at a –4 penalty on attack rolls. You can shoot a heavy crossbow with each hand, but you take a penalty on attack rolls as if attacking with two one-handed weapons. This penalty is cumulative with the penalty for one-handed firing.",
            'cost' => 50,
            'dmg_small' => '1d8',
            'dmg_medium' => '1d10',
            'critical' => '19-20/x2',
            'range' => 120,
            'weight_small' => 4,
            'weight_medium' => 8,
            'type' => 'P',
            'special' => '',
        ), array(
            'name' => 'Light Crossbow',
            'category' => 'Simple Weapons',
            'subcategory' => 'Ranged Weapons',
            'description' => "You draw a light crossbow back by pulling a lever. Loading a light crossbow is a move action that provokes attacks of opportunity. Normally, operating a light crossbow requires two hands. However, you can shoot, but not load, a light crossbow with one hand at a –2 penalty on attack rolls. You can shoot a light crossbow with each hand, but you take a penalty on attack rolls as if attacking with two light weapons. This penalty is cumulative with the penalty for one-handed firing.",
            'cost' => 35,
            'dmg_small' => '1d6',
            'dmg_medium' => '1d8',
            'critical' => '19-20/x2',
            'range' => 80,
            'weight_small' => 2,
            'weight_medium' => 4,
            'type' => 'P',
            'special' => '',
        ), array(
            'name' => 'Dart',
            'category' => 'Simple Weapons',
            'subcategory' => 'Ranged Weapons',
            'description' => "Throwing weapon.",
            'cost' => 0.5,
            'dmg_small' => '1d3',
            'dmg_medium' => '1d4',
            'critical' => 'x2',
            'range' => 20,
            'weight_small' => 0.25,
            'weight_medium' => 0.5,
            'type' => 'P',
            'special' => '',
        ), array(
            'name' => 'Javelin',
            'category' => 'Simple Weapons',
            'subcategory' => 'Ranged Weapons',
            'description' => "A javelin is a thin throwing spear . Since it is not designed for melee, you are treated as nonproficient with it and take a –4 penalty on attack rolls if you use a javelin as a melee weapon.",
            'cost' => 1,
            'dmg_small' => '1d4',
            'dmg_medium' => '1d6',
            'critical' => 'x2',
            'range' => 30,
            'weight_small' => 1,
            'weight_medium' => 2,
            'type' => 'P',
            'special' => '',
        ), array(
            'name' => 'Sling',
            'category' => 'Simple Weapons',
            'subcategory' => 'Ranged Weapons',
            'description' => "A sling is little more than a leather cup attached to a pair of strings. Your Strength modifier applies to damage rolls when you use a sling, just as it does for thrown weapons. You can fire, but not load, a sling with one hand. Loading a sling is a move action that requires two hands and provokes attacks of opportunity. You can hurl ordinary stones with a sling, but stones are not as dense or as round as bullets. Thus, such an attack deals damage as if the weapon were designed for a creature one size category smaller than you and you take a –1 penalty on attack rolls.",
            'cost' => 0,
            'dmg_small' => '1d3',
            'dmg_medium' => '1d4',
            'critical' => 'x2',
            'range' => 50,
            'weight_small' => 0,
            'weight_medium' => 0,
            'type' => 'B',
            'special' => '',
        ), array(
            'name' => 'Throwing Axe',
            'category' => 'Martial Weapons',
            'subcategory' => 'Light Melee Weapons',
            'description' => "Throwing weapon.",
            'cost' => 8,
            'dmg_small' => '1d4',
            'dmg_medium' => '1d6',
            'critical' => 'x2',
            'range' => 10,
            'weight_small' => 1,
            'weight_medium' => 2,
            'type' => 'S',
            'special' => '',
        ), array(
            'name' => 'Light Hammer',
            'category' => 'Martial Weapons',
            'subcategory' => 'Light Melee Weapons',
            'description' => "Throwing weapon.",
            'cost' => 1,
            'dmg_small' => '1d3',
            'dmg_medium' => '1d4',
            'critical' => 'x2',
            'range' => 20,
            'weight_small' => 1,
            'weight_medium' => 2,
            'type' => 'B',
            'special' => '',
        ), array(
            'name' => 'Handaxe',
            'category' => 'Martial Weapons',
            'subcategory' => 'Light Melee Weapons',
            'description' => "",
            'cost' => 6,
            'dmg_small' => '1d4',
            'dmg_medium' => '1d6',
            'critical' => 'x3',
            'range' => null,
            'weight_small' => 1.5,
            'weight_medium' => 3,
            'type' => 'S',
            'special' => '',
        ), array(
            'name' => 'Kukri',
            'category' => 'Martial Weapons',
            'subcategory' => 'Light Melee Weapons',
            'description' => "A kukri is a curved blade, about 1 foot in length.",
            'cost' => 8,
            'dmg_small' => '1d3',
            'dmg_medium' => '1d4',
            'critical' => '18-20/x2',
            'range' => null,
            'weight_small' => 1,
            'weight_medium' => 2,
            'type' => 'S',
            'special' => '',
        ), array(
            'name' => 'Light Pick',
            'category' => 'Martial Weapons',
            'subcategory' => 'Light Melee Weapons',
            'description' => "",
            'cost' => 4,
            'dmg_small' => '1d3',
            'dmg_medium' => '1d4',
            'critical' => 'x4',
            'range' => null,
            'weight_small' => 1.5,
            'weight_medium' => 3,
            'type' => 'P',
            'special' => '',
        ), array(
            'name' => 'Sap',
            'category' => 'Martial Weapons',
            'subcategory' => 'Light Melee Weapons',
            'description' => "",
            'cost' => 1,
            'dmg_small' => '1d4',
            'dmg_medium' => '1d6',
            'critical' => 'x2',
            'range' => null,
            'weight_small' => 1,
            'weight_medium' => 2,
            'type' => 'B',
            'special' => 'nonlethal',
        ), array(
            'name' => 'Light Shield',
            'category' => 'Martial Weapons',
            'subcategory' => 'Light Melee Weapons',
            'description' => "You can bash with a shield instead of using it for defense.",
            'cost' => null,
            'dmg_small' => '1d2',
            'dmg_medium' => '1d3',
            'critical' => 'x2',
            'range' => null,
            'weight_small' => null,
            'weight_medium' => null,
            'type' => 'B',
            'special' => '',
        ), array(
            'name' => 'Spiked armor',
            'category' => 'Martial Weapons',
            'subcategory' => 'Light Melee Weapons',
            'description' => "You can outfit your armor with spikes, which can deal damage in a grapple or as a separate attack. See Armor, below, for details.",
            'cost' => null,
            'dmg_small' => '1d4',
            'dmg_medium' => '1d6',
            'critical' => 'x2',
            'range' => null,
            'weight_small' => null,
            'weight_medium' => null,
            'type' => 'P',
            'special' => '',
        ), array(
            'name' => 'Light Spiked Shield',
            'category' => 'Martial Weapons',
            'subcategory' => 'Light Melee Weapons',
            'description' => "You can bash with a shield instead of using it for defense.",
            'cost' => null,
            'dmg_small' => '1d3',
            'dmg_medium' => '1d4',
            'critical' => 'x2',
            'range' => null,
            'weight_small' => null,
            'weight_medium' => null,
            'type' => 'P',
            'special' => '',
        ), array(
            'name' => 'Starknife',
            'category' => 'Martial Weapons',
            'subcategory' => 'Light Melee Weapons',
            'description' => "From a central metal ring, four tapering metal blades extend like points on a compass rose. A wielder can stab with the starknife or throw it. ",
            'cost' => 24,
            'dmg_small' => '1d3',
            'dmg_medium' => '1d4',
            'critical' => 'x3',
            'range' => 20,
            'weight_small' => 1.5,
            'weight_medium' => 3,
            'type' => 'P',
            'special' => '',
        ), array(
            'name' => 'Shortsword',
            'category' => 'Martial Weapons',
            'subcategory' => 'Light Melee Weapons',
            'description' => "This sword is about 2 feet in length.",
            'cost' => 10,
            'dmg_small' => '1d4',
            'dmg_medium' => '1d6',
            'critical' => '19-20/x2',
            'range' => null,
            'weight_small' => 1,
            'weight_medium' => 2,
            'type' => 'P',
            'special' => '',
        ), array(
            'name' => 'Battleaxe',
            'category' => 'Martial Weapons',
            'subcategory' => 'One-Handed Melee Weapons',
            'description' => "",
            'cost' => 10,
            'dmg_small' => '1d6',
            'dmg_medium' => '1d8',
            'critical' => 'x3',
            'range' => null,
            'weight_small' => 3,
            'weight_medium' => 6,
            'type' => 'S',
            'special' => '',
        ), array(
            'name' => 'Flail',
            'category' => 'Martial Weapons',
            'subcategory' => 'One-Handed Melee Weapons',
            'description' => "A flail consists of a spiked metal ball, connected to a handle by a sturdy chain.",
            'cost' => 8,
            'dmg_small' => '1d6',
            'dmg_medium' => '1d8',
            'critical' => 'x2',
            'range' => null,
            'weight_small' => 2.5,
            'weight_medium' => 5,
            'type' => 'B',
            'special' => 'disarm, trip',
        ), array(
            'name' => 'Longsword',
            'category' => 'Martial Weapons',
            'subcategory' => 'One-Handed Melee Weapons',
            'description' => "This sword is about 3-1/2 feet in length.",
            'cost' => 15,
            'dmg_small' => '1d6',
            'dmg_medium' => '1d8',
            'critical' => '19-20/x2',
            'range' => null,
            'weight_small' => 2,
            'weight_medium' => 4,
            'type' => 'S',
            'special' => '',
        ), array(
            'name' => 'Heavy Pick',
            'category' => 'Martial Weapons',
            'subcategory' => 'One-Handed Melee Weapons',
            'description' => "",
            'cost' => 8,
            'dmg_small' => '1d4',
            'dmg_medium' => '1d6',
            'critical' => 'x4',
            'range' => null,
            'weight_small' => 3,
            'weight_medium' => 6,
            'type' => 'P',
            'special' => '',
        ), array(
            'name' => 'Rapier',
            'category' => 'Martial Weapons',
            'subcategory' => 'One-Handed Melee Weapons',
            'description' => "You can use the Weapon Finesse feat to apply your Dexterity modifier instead of your Strength modifier to attack rolls with a rapier sized for you, even though it isn't a light weapon. You can't wield a rapier in two hands in order to apply 1-1/2 times your Strength bonus to damage.",
            'cost' => 20,
            'dmg_small' => '1d4',
            'dmg_medium' => '1d6',
            'critical' => '18-20/x2',
            'range' => null,
            'weight_small' => 1,
            'weight_medium' => 2,
            'type' => 'P',
            'special' => '',
        ), array(
            'name' => 'Scimitar',
            'category' => 'Martial Weapons',
            'subcategory' => 'One-Handed Melee Weapons',
            'description' => "A scimitar is a curved sword.",
            'cost' => 15,
            'dmg_small' => '1d4',
            'dmg_medium' => '1d6',
            'critical' => '18-20/x2',
            'range' => null,
            'weight_small' => 2,
            'weight_medium' => 4,
            'type' => 'S',
            'special' => '',
        ), array(
            'name' => 'Heavy Shield',
            'category' => 'Martial Weapons',
            'subcategory' => 'One-Handed Melee Weapons',
            'description' => "You can bash with a shield instead of using it for defense.",
            'cost' => null,
            'dmg_small' => '1d3',
            'dmg_medium' => '1d4',
            'critical' => 'x2',
            'range' => null,
            'weight_small' => null,
            'weight_medium' => null,
            'type' => 'B',
            'special' => '',
        ), array(
            'name' => 'Heavy Spiked Shield',
            'category' => 'Martial Weapons',
            'subcategory' => 'One-Handed Melee Weapons',
            'description' => "You can bash with a shield instead of using it for defense.",
            'cost' => null,
            'dmg_small' => '1d4',
            'dmg_medium' => '1d6',
            'critical' => 'x2',
            'range' => null,
            'weight_small' => null,
            'weight_medium' => null,
            'type' => 'P',
            'special' => '',
        ), array(
            'name' => 'Trident',
            'category' => 'Martial Weapons',
            'subcategory' => 'One-Handed Melee Weapons',
            'description' => "A trident has three metal prongs at end of a 4-foot-long shaft. This weapon can be thrown.",
            'cost' => 15,
            'dmg_small' => '1d6',
            'dmg_medium' => '1d8',
            'critical' => 'x2',
            'range' => 10,
            'weight_small' => 2,
            'weight_medium' => 4,
            'type' => 'P',
            'special' => 'brace',
        ), array(
            'name' => 'Warhammer',
            'category' => 'Martial Weapons',
            'subcategory' => 'One-Handed Melee Weapons',
            'description' => "",
            'cost' => 12,
            'dmg_small' => '1d6',
            'dmg_medium' => '1d8',
            'critical' => 'x3',
            'range' => null,
            'weight_small' => 2.5,
            'weight_medium' => 5,
            'type' => 'B',
            'special' => '',
        ), array(
            'name' => 'Falchion',
            'category' => 'Martial Weapons',
            'subcategory' => 'Two-Handed Melee Weapons',
            'description' => "",
            'cost' => 75,
            'dmg_small' => '1d6',
            'dmg_medium' => '2d4',
            'critical' => '18-20/x2',
            'range' => null,
            'weight_small' => 4,
            'weight_medium' => 8,
            'type' => 'S',
            'special' => '',
        ), array(
            'name' => 'Glaive',
            'category' => 'Martial Weapons',
            'subcategory' => 'Two-Handed Melee Weapons',
            'description' => "A glaive is a simple blade, mounted to the end of a pole about 7 feet in length.",
            'cost' => 8,
            'dmg_small' => '1d8',
            'dmg_medium' => '1d10',
            'critical' => 'x3',
            'range' => null,
            'weight_small' => 5,
            'weight_medium' => 10,
            'type' => 'S',
            'special' => 'reach',
        ), array(
            'name' => 'Greataxe',
            'category' => 'Martial Weapons',
            'subcategory' => 'Two-Handed Melee Weapons',
            'description' => "",
            'cost' => 20,
            'dmg_small' => '1d10',
            'dmg_medium' => '1d12',
            'critical' => 'x3',
            'range' => null,
            'weight_small' => 6,
            'weight_medium' => 12,
            'type' => 'S',
            'special' => '',
        ), array(
            'name' => 'Greatclub',
            'category' => 'Martial Weapons',
            'subcategory' => 'Two-Handed Melee Weapons',
            'description' => "",
            'cost' => 5,
            'dmg_small' => '1d8',
            'dmg_medium' => '1d10',
            'critical' => 'x2',
            'range' => null,
            'weight_small' => 4,
            'weight_medium' => 8,
            'type' => 'B',
            'special' => '',
        ), array(
            'name' => 'Heavy Flail',
            'category' => 'Martial Weapons',
            'subcategory' => 'Two-Handed Melee Weapons',
            'description' => "Similar to a flail, a heavy flail has a larger metal ball and a longer handle.",
            'cost' => 15,
            'dmg_small' => '1d8',
            'dmg_medium' => '1d10',
            'critical' => '19-20/x2',
            'range' => null,
            'weight_small' => 5,
            'weight_medium' => 10,
            'type' => 'B',
            'special' => 'disarm, trip',
        ), array(
            'name' => 'Greatsword',
            'category' => 'Martial Weapons',
            'subcategory' => 'Two-Handed Melee Weapons',
            'description' => "This immense two-handed sword is about 5 feet in length.",
            'cost' => 50,
            'dmg_small' => '1d10',
            'dmg_medium' => '2d6',
            'critical' => '19-20/x2',
            'range' => null,
            'weight_small' => 4,
            'weight_medium' => 8,
            'type' => 'S',
            'special' => '',
        ), array(
            'name' => 'Guisarme',
            'category' => 'Martial Weapons',
            'subcategory' => 'Two-Handed Melee Weapons',
            'description' => "A guisarme is an 8-foot-long shaft with a blade and a hook mounted at the tip.",
            'cost' => 9,
            'dmg_small' => '1d6',
            'dmg_medium' => '2d4',
            'critical' => 'x3',
            'range' => null,
            'weight_small' => 6,
            'weight_medium' => 12,
            'type' => 'S',
            'special' => 'reach, trip',
        ), array(
            'name' => 'Halberd',
            'category' => 'Martial Weapons',
            'subcategory' => 'Two-Handed Melee Weapons',
            'description' => "A halberd is similar to a 5-foot-long spear, but it also has a small, axe-like head mounted near the tip.",
            'cost' => 10,
            'dmg_small' => '1d8',
            'dmg_medium' => '1d10',
            'critical' => 'x3',
            'range' => null,
            'weight_small' => 6,
            'weight_medium' => 12,
            'type' => 'P or S',
            'special' => 'brace, trip',
        ), array(
            'name' => 'Lance',
            'category' => 'Martial Weapons',
            'subcategory' => 'Two-Handed Melee Weapons',
            'description' => "A lance deals double damage when used from the back of a charging mount. While mounted, you can wield a lance with one hand.",
            'cost' => 10,
            'dmg_small' => '1d6',
            'dmg_medium' => '1d8',
            'critical' => 'x3',
            'range' => null,
            'weight_small' => 5,
            'weight_medium' => 10,
            'type' => 'P',
            'special' => 'reach',
        ), array(
            'name' => 'Ranseur',
            'category' => 'Martial Weapons',
            'subcategory' => 'Two-Handed Melee Weapons',
            'description' => "Similar in appearance to a trident, a ranseur has a single spear at its tip, flanked by a pair of short, curving blades.",
            'cost' => 10,
            'dmg_small' => '1d6',
            'dmg_medium' => '2d4',
            'critical' => 'x3',
            'range' => null,
            'weight_small' => 6,
            'weight_medium' => 12,
            'type' => 'P',
            'special' => 'disarm, reach',
        ), array(
            'name' => 'Scythe',
            'category' => 'Martial Weapons',
            'subcategory' => 'Two-Handed Melee Weapons',
            'description' => "",
            'cost' => 18,
            'dmg_small' => '1d6',
            'dmg_medium' => '2d4',
            'critical' => 'x4',
            'range' => null,
            'weight_small' => 5,
            'weight_medium' => 10,
            'type' => 'P or S',
            'special' => 'trip',
        ), array(
            'name' => 'Longbow',
            'category' => 'Martial Weapons',
            'subcategory' => 'Ranged Weapons',
            'description' => "At almost 5 feet in height, a longbow is made up of one solid piece of carefully curved wood. You need two hands to use a bow, regardless of its size. A longbow is too unwieldy to use while you are mounted. If you have a penalty for low Strength, apply it to damage rolls when you use a longbow. If you have a Strength bonus, you can apply it to damage rolls when you use a composite longbow (see below), but not when you use a regular longbow.",
            'cost' => 75,
            'dmg_small' => '1d6',
            'dmg_medium' => '1d8',
            'critical' => 'x3',
            'range' => 100,
            'weight_small' => 1.5,
            'weight_medium' => 3,
            'type' => 'P',
            'special' => '',
        ), array(
            'name' => 'Composite Longbow',
            'category' => 'Martial Weapons',
            'subcategory' => 'Ranged Weapons',
            'description' => "You need at least two hands to use a bow, regardless of its size. You can use a composite longbow while mounted. All composite bows are made with a particular strength rating (that is, each requires a minimum Strength modifier to use with proficiency). If your Strength bonus is less than the strength rating of the composite bow, you can't effectively use it, so you take a –2 penalty on attacks with it. The default composite longbow requires a Strength modifier of +0 or higher to use with proficiency. A composite longbow can be made with a high strength rating to take advantage of an above-average Strength score; this feature allows you to add your Strength bonus to damage, up to the maximum bonus indicated for the bow. Each point of Strength bonus granted by the bow adds 100 gp to its cost. If you have a penalty for low Strength, apply it to damage rolls when you use a composite longbow. For purposes of Weapon Proficiency and similar feats, a composite longbow is treated as if it were a longbow.",
            'cost' => 100,
            'dmg_small' => '1d6',
            'dmg_medium' => '1d8',
            'critical' => 'x3',
            'range' => 110,
            'weight_small' => 1.5,
            'weight_medium' => 3,
            'type' => 'P',
            'special' => '',
        ), array(
            'name' => 'Shortbow',
            'category' => 'Martial Weapons',
            'subcategory' => 'Ranged Weapons',
            'description' => "A shortbow is made up of one piece of wood, about 3 feet in length. You need two hands to use a bow, regardless of its size. You can use a shortbow while mounted. If you have a penalty for low Strength, apply it to damage rolls when you use a shortbow. If you have a bonus for high Strength, you can apply it to damage rolls when you use a composite shortbow (see below), but not a regular shortbow.",
            'cost' => 30,
            'dmg_small' => '1d4',
            'dmg_medium' => '1d6',
            'critical' => 'x3',
            'range' => 60,
            'weight_small' => 1,
            'weight_medium' => 2,
            'type' => 'P',
            'special' => '',
        ), array(
            'name' => 'Composite Shortbow',
            'category' => 'Martial Weapons',
            'subcategory' => 'Ranged Weapons',
            'description' => "You need at least two hands to use a bow, regardless of its size. You can use a composite shortbow while mounted. All composite bows are made with a particular strength rating (that is, each requires a minimum Strength modifier to use with proficiency). If your Strength bonus is lower than the strength rating of the composite bow, you can't effectively use it, so you take a –2 penalty on attacks with it. The default composite shortbow requires a Strength modifier of +0 or higher to use with proficiency. A composite shortbow can be made with a high strength rating to take advantage of an above-average Strength score; this feature allows you to add your Strength bonus to damage, up to the maximum bonus indicated for the bow. Each point of Strength bonus granted by the bow adds 75 gp to its cost. If you have a penalty for low Strength, apply it to damage rolls when you use a composite shortbow. For purposes of Weapon Proficiency, Weapon Focus, and similar feats, a composite shortbow is treated as if it were a shortbow.",
            'cost' => 75,
            'dmg_small' => '1d4',
            'dmg_medium' => '1d6',
            'critical' => 'x3',
            'range' => 70,
            'weight_small' => 1,
            'weight_medium' => 2,
            'type' => 'P',
            'special' => '',
        ), array(
            'name' => 'Kama',
            'category' => 'Exotic Weapons',
            'subcategory' => 'Light Melee Weapons',
            'description' => "Similar to a sickle, a kama is a short, curved blade attached to a simple handle.",
            'cost' => 2,
            'dmg_small' => '1d4',
            'dmg_medium' => '1d6',
            'critical' => 'x2',
            'range' => null,
            'weight_small' => 1,
            'weight_medium' => 2,
            'type' => 'S',
            'special' => 'monk, trip',
        ), array(
            'name' => 'Nunchaku',
            'category' => 'Exotic Weapons',
            'subcategory' => 'Light Melee Weapons',
            'description' => "A nunchaku is made up of two wooden or metal bars connected by a small length of rope or chain.",
            'cost' => 2,
            'dmg_small' => '1d4',
            'dmg_medium' => '1d6',
            'critical' => 'x2',
            'range' => null,
            'weight_small' => 1,
            'weight_medium' => 2,
            'type' => 'B',
            'special' => 'disarm, monk',
        ), array(
            'name' => 'Sai',
            'category' => 'Exotic Weapons',
            'subcategory' => 'Light Melee Weapons',
            'description' => "A sai is a metal spike flanked by a pair of prongs used to trap an enemy's weapon. With a sai, you get a +2 bonus on Combat Maneuver Checks to sunder an enemy's weapon. Though pointed, a sai is used primarily to bludgeon foes and to disarm weapons.",
            'cost' => 1,
            'dmg_small' => '1d3',
            'dmg_medium' => '1d4',
            'critical' => 'x2',
            'range' => null,
            'weight_small' => 0.5,
            'weight_medium' => 1,
            'type' => 'B',
            'special' => 'disarm, monk',
        ), array(
            'name' => 'Siangham',
            'category' => 'Exotic Weapons',
            'subcategory' => 'Light Melee Weapons',
            'description' => "This weapon is a handheld shaft fitted with a pointed tip for stabbing foes.",
            'cost' => 3,
            'dmg_small' => '1d4',
            'dmg_medium' => '1d6',
            'critical' => 'x2',
            'range' => null,
            'weight_small' => 0.5,
            'weight_medium' => 1,
            'type' => 'P',
            'special' => 'monk',
        ), array(
            'name' => 'Bastard Sword',
            'category' => 'Exotic Weapons',
            'subcategory' => 'One-Handed Melee Weapons',
            'description' => "A bastard sword is about 4 feet in length, making it too large to use in one hand without special training; thus, it is an exotic weapon. A character can use a bastard sword two-handed as a martial weapon.",
            'cost' => 35,
            'dmg_small' => '1d8',
            'dmg_medium' => '1d10',
            'critical' => '19-20/x2',
            'range' => null,
            'weight_small' => 3,
            'weight_medium' => 6,
            'type' => 'S',
            'special' => '',
        ), array(
            'name' => 'Dwarven Waraxe',
            'category' => 'Exotic Weapons',
            'subcategory' => 'One-Handed Melee Weapons',
            'description' => "A dwarven waraxe has a large, ornate head mounted to a thick handle, making it too large to use in one hand without special training; thus, it is an exotic weapon. A Medium character can use a dwarven waraxe two-handed as a martial weapon, or a Large creature can use it one-handed in the same way. A dwarf treats a dwarven waraxe as a martial weapon even when using it in one hand.",
            'cost' => 30,
            'dmg_small' => '1d8',
            'dmg_medium' => '1d10',
            'critical' => 'x3',
            'range' => null,
            'weight_small' => 4,
            'weight_medium' => 8,
            'type' => 'S',
            'special' => '',
        ), array(
            'name' => 'Whip',
            'category' => 'Exotic Weapons',
            'subcategory' => 'One-Handed Melee Weapons',
            'description' => "A whip deals no damage to any creature with an armor bonus of +1 or higher or a natural armor bonus of +3 or higher. The whip is treated as a melee weapon with 15-foot reach, though you don't threaten the area into which you can make an attack. In addition, unlike most other weapons with reach, you can use it against foes anywhere within your reach (including adjacent foes). Using a whip provokes an attack of opportunity, just as if you had used a ranged weapon. You can use the Weapon Finesse feat to apply your Dexterity modifier instead of your Strength modifier to attack rolls with a whip sized for you, even though it isn't a light weapon.",
            'cost' => 1,
            'dmg_small' => '1d2',
            'dmg_medium' => '1d3',
            'critical' => 'x2',
            'range' => null,
            'weight_small' => 1,
            'weight_medium' => 2,
            'type' => 'S',
            'special' => 'disarm, nonlethal, reach, trip',
        ), array(
            'name' => 'Orc Double Axe',
            'category' => 'Exotic Weapons',
            'subcategory' => 'Two-Handed Melee Weapons',
            'description' => "A cruel weapon with blades placed at opposite ends of a long haft, an orc double axe is a double weapon.",
            'cost' => 60,
            'dmg_small' => '1d6/1d6',
            'dmg_medium' => '1d8/1d8',
            'critical' => 'x3',
            'range' => null,
            'weight_small' => 7.5,
            'weight_medium' => 15,
            'type' => 'S',
            'special' => 'double',
        ), array(
            'name' => 'Spiked Chain',
            'category' => 'Exotic Weapons',
            'subcategory' => 'Two-Handed Melee Weapons',
            'description' => "A spiked chain is about 4 feet in length, covered in wicked barbs. You can use the Weapon Finesse feat to apply your Dexterity modifier instead of your Strength modifier to attack rolls with a spiked chain sized for you, even though it isn't a light weapon.",
            'cost' => 25,
            'dmg_small' => '1d6',
            'dmg_medium' => '2d4',
            'critical' => 'x2',
            'range' => null,
            'weight_small' => 5,
            'weight_medium' => 10,
            'type' => 'P',
            'special' => 'disarm, trip',
        ), array(
            'name' => 'Elven Curve Blade',
            'category' => 'Exotic Weapons',
            'subcategory' => 'Two-Handed Melee Weapons',
            'description' => "Essentially a longer version of a scimitar, but with a thinner blade, the elven curve blade is exceptionally rare. You receive a +2 circumstance bonus to your Combat Maneuver Defense whenever a foe attempts to sunder your elven curve blade due to its flexible metal. You can use the Weapon Finesse feat to apply your Dexterity modifier instead of your Strength modifier to attack rolls with an elven curve blade sized for you, even though it isn't a light weapon.",
            'cost' => 80,
            'dmg_small' => '1d8',
            'dmg_medium' => '1d10',
            'critical' => '18-20/x2',
            'range' => null,
            'weight_small' => 3.5,
            'weight_medium' => 7,
            'type' => 'S',
            'special' => '',
        ), array(
            'name' => 'Dire Flail',
            'category' => 'Exotic Weapons',
            'subcategory' => 'Two-Handed Melee Weapons',
            'description' => "A dire flail consists of two spheres of spiked iron dangling from chains at opposite ends of a long haft.",
            'cost' => 90,
            'dmg_small' => '1d6/1d6',
            'dmg_medium' => '1d8/1d8',
            'critical' => 'x2',
            'range' => null,
            'weight_small' => 5,
            'weight_medium' => 10,
            'type' => 'B',
            'special' => 'disarm, double, trip',
        ), array(
            'name' => 'Gnome Hooked Hammer',
            'category' => 'Exotic Weapons',
            'subcategory' => 'Two-Handed Melee Weapons',
            'description' => "A gnome hooked hammer is a double weapon—an ingenious tool with a hammer head at one end of its haft and a long, curved pick at the other. The hammer's blunt head is a bludgeoning weapon that deals 1d6 points of damage (crit ×3). Its hook is a piercing weapon that deals 1d4 points of damage (crit ×4). You can use either head as the primary weapon. Gnomes treat hooked hammers as martial weapons.",
            'cost' => 20,
            'dmg_small' => '1d6/1d4',
            'dmg_medium' => '1d8/1d6',
            'critical' => 'x3/x4',
            'range' => null,
            'weight_small' => 3,
            'weight_medium' => 6,
            'type' => 'B or P',
            'special' => 'double, trip',
        ), array(
            'name' => 'Two-bladed Sword',
            'category' => 'Exotic Weapons',
            'subcategory' => 'Two-Handed Melee Weapons',
            'description' => "A two-bladed sword is a double weapon—twin blades extend from either side of a central, short haft, allowing the wielder to attack with graceful but deadly flourishes.",
            'cost' => 100,
            'dmg_small' => '1d6/1d6',
            'dmg_medium' => '1d8/1d8',
            'critical' => '19-20/x2',
            'range' => null,
            'weight_small' => 5,
            'weight_medium' => 10,
            'type' => 'S',
            'special' => 'double',
        ), array(
            'name' => 'Dwarven Urgrosh',
            'category' => 'Exotic Weapons',
            'subcategory' => 'Two-Handed Melee Weapons',
            'description' => "A dwarven urgrosh is a double weapon—an axe head and a spear point on opposite ends of a long haft. The urgrosh's axe head is a slashing weapon that deals 1d8 points of damage. Its spear head is a piercing weapon that deals 1d6 points of damage. You can use either head as the primary weapon. The other becomes the off-hand weapon. If you use an urgrosh against a charging character, the spear head is the part of the weapon that deals damage. Dwarves treat dwarven urgroshes as martial weapons.",
            'cost' => 50,
            'dmg_small' => '1d6/1d4',
            'dmg_medium' => '1d8/1d6',
            'critical' => 'x3',
            'range' => null,
            'weight_small' => 6,
            'weight_medium' => 12,
            'type' => 'P or S',
            'special' => 'brace, double',
        ), array(
            'name' => 'Bolas',
            'category' => 'Exotic Weapons',
            'subcategory' => 'Ranged Weapons',
            'description' => "A bolas is a pair of weights, connected by a thin rope or cord. You can use this weapon to make a ranged trip attack against an opponent. You can't be tripped during your own trip attempt when using a bolas.",
            'cost' => 5,
            'dmg_small' => '1d3',
            'dmg_medium' => '1d4',
            'critical' => 'x2',
            'range' => 10,
            'weight_small' => 1,
            'weight_medium' => 2,
            'type' => 'B',
            'special' => 'nonlethal, trip',
        ), array(
            'name' => 'Hand Crossbow',
            'category' => 'Exotic Weapons',
            'subcategory' => 'Ranged Weapons',
            'description' => "You can draw a hand crossbow back by hand. Loading a hand crossbow is a move action that provokes attacks of opportunity. You can shoot, but not load, a hand crossbow with one hand at no penalty. You can shoot a hand crossbow with each hand, but you take a penalty on attack rolls as if attacking with two light weapons.",
            'cost' => 100,
            'dmg_small' => '1d3',
            'dmg_medium' => '1d4',
            'critical' => '19-20/x2',
            'range' => 30,
            'weight_small' => 1,
            'weight_medium' => 2,
            'type' => 'P',
            'special' => '',
        ), array(
            'name' => 'Repeating Heavy Crossbow',
            'category' => 'Exotic Weapons',
            'subcategory' => 'Ranged Weapons',
            'description' => "The repeating crossbow (whether heavy or light) holds 5 crossbow bolts. As long as it holds bolts, you can reload it by pulling the reloading lever (a free action). Loading a new case of 5 bolts is a full-round action that provokes attacks of opportunity. You can fire a repeating crossbow with one hand or fire a repeating crossbow in each hand in the same manner as you would a normal crossbow of the same size. However, you must fire the weapon with two hands in order to use the reloading lever, and you must use two hands to load a new case of bolts.",
            'cost' => 400,
            'dmg_small' => '1d8',
            'dmg_medium' => '1d10',
            'critical' => '19-20/x2',
            'range' => 120,
            'weight_small' => 6,
            'weight_medium' => 12,
            'type' => 'P',
            'special' => '',
        ), array(
            'name' => 'Repeating Light Crossbow',
            'category' => 'Exotic Weapons',
            'subcategory' => 'Ranged Weapons',
            'description' => "The repeating crossbow (whether heavy or light) holds 5 crossbow bolts. As long as it holds bolts, you can reload it by pulling the reloading lever (a free action). Loading a new case of 5 bolts is a full-round action that provokes attacks of opportunity. You can fire a repeating crossbow with one hand or fire a repeating crossbow in each hand in the same manner as you would a normal crossbow of the same size. However, you must fire the weapon with two hands in order to use the reloading lever, and you must use two hands to load a new case of bolts.",
            'cost' => 250,
            'dmg_small' => '1d6',
            'dmg_medium' => '1d8',
            'critical' => '19-20/x2',
            'range' => 80,
            'weight_small' => 3,
            'weight_medium' => 6,
            'type' => 'P',
            'special' => '',
        ), array(
            'name' => 'Net',
            'category' => 'Exotic Weapons',
            'subcategory' => 'Ranged Weapons',
            'description' => "A net is used to entangle enemies. When you throw a net, you make a ranged touch attack against your target. A net's maximum range is 10 feet. If you hit, the target is entangled. An entangled creature takes a –2 penalty on attack rolls and a –4 penalty on Dexterity, can move at only half speed, and cannot charge or run. If you control the trailing rope by succeeding on an opposed Strength check while holding it, the entangled creature can move only within the limits that the rope allows. If the entangled creature attempts to cast a spell, it must make a concentration check with a DC of 15 + the spell's level or be unable to cast the spell. An entangled creature can escape with a DC 20 Escape Artist check (a full-round action). The net has 5 hit points and can be burst with a DC 25 Strength check (also a full-round action). A net is useful only against creatures within one size category of you. A net must be folded to be thrown effectively. The first time you throw your net in a fight, you make a normal ranged touch attack roll. After the net is unfolded, you take a –4 penalty on attack rolls with it. It takes 2 rounds for a proficient user to fold a net and twice that long for a nonproficient one to do so.",
            'cost' => 20,
            'dmg_small' => '',
            'dmg_medium' => '',
            'critical' => '',
            'range' => 10,
            'weight_small' => 3,
            'weight_medium' => 6,
            'type' => '',
            'special' => '',
        ), array(
            'name' => 'Shuriken',
            'category' => 'Exotic Weapons',
            'subcategory' => 'Ranged Weapons',
            'description' => "A shuriken is a small piece of metal with sharpened edges, designed for throwing. A shuriken can't be used as a melee weapon. Although they are thrown weapons, shuriken are treated as ammunition for the purposes of drawing them, crafting masterwork or otherwise special versions of them, and what happens to them after they are thrown.",
            'cost' => 1,
            'dmg_small' => '1',
            'dmg_medium' => '1d2',
            'critical' => 'x2',
            'range' => 10,
            'weight_small' => 0.25,
            'weight_medium' => 0.5,
            'type' => 'P',
            'special' => 'monk',
        ), array(
            'name' => 'Halfling Sling Staff',
            'category' => 'Exotic Weapons',
            'subcategory' => 'Ranged Weapons',
            'description' => "Made from a specially designed sling attached to a short club, a halfling sling staff can be used by a proficient wielder to devastating effect. Your Strength modifier applies to damage rolls when you use a halfling sling staff, just as it does for thrown weapons. You can fire, but not load, a halfling sling staff with one hand. Loading a halfling sling staff is a move action that requires two hands and provokes attacks of opportunity. You can hurl ordinary stones with a halfling sling staff, but stones are not as dense or as round as bullets. Thus, such an attack deals damage as if the weapon were designed for a creature one size category smaller than you and you take a –1 penalty on attack rolls. A halfling sling staff can be used as a simple weapon that deals bludgeoning damage equal to that of a club of its size. Halflings treat halfling sling staves as martial weapons.",
            'cost' => 20,
            'dmg_small' => '1d6',
            'dmg_medium' => '1d8',
            'critical' => 'x3',
            'range' => 80,
            'weight_small' => 1.5,
            'weight_medium' => 3,
            'type' => 'B',
            'special' => '',
        )));
	}


	/**
	 * Reverse the migrations.
	 *
	 * @return void
	 */
	public function down()
	{
		Schema::drop('weapons');
	}

}
