<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;

class CreateFeats extends Migration {

	/**
	 * Run the migrations.
	 *
	 * @return void
	 */
	public function up()
	{
		Schema::create('feats', function(Blueprint $table) {
			$table->increments('feat_id');
			$table->string('name');
			$table->string('feat_type');
            $table->string('prerequisites')->nullable();
			$table->string('effect')->nullable();
            $table->string('description')->nullable();
			$table->string('benefit');
			$table->string('special')->nullable();
		});

        Db::table('feats')->insert(array(array(
            'name' => 'Acrobatic',
            'feat_type' => 'Skill Bonus',
            'prerequisites' => '',
            'effect' => 'Acrobatics, Fly',
            'description' => "You are skilled at leaping, jumping, and flying.",
            'benefit' => "You get a +2 bonus on all Acrobatics and Fly skill checks. If you have 10 or more ranks in one of these skills, the bonus increases to +4 for that skill.",
            'special' => "",
        ), array(
            'name' => 'Acrobatic Steps',
            'feat_type' => 'Movement',
            'prerequisites' => 'DEX:15, Nimble Moves',
            'effect' => '',
            'description' => "You can easily move over and through obstacles.",
            'benefit' => "Whenever you move, you may move through up to 15 feet of difficult terrain each round as if it were normal terrain. The effects of this feat stack with those provided by Nimble Moves (allowing you to move normally through a total of 20 feet of difficult terrain each round).",
            'special' => "",
        ), array(
            'name' => 'Agile Maneuvers (Combat)',
            'feat_type' => 'General',
            'prerequisites' => '',
            'effect' => 'CMB gets DEX in place of STR',
            'description' => "You've learned to use your quickness in place of brute force when performing combat maneuvers.",
            'benefit' => "You add your Dexterity bonus to your base attack bonus and size bonus when determining your Combat Maneuver Bonus (see Combat) instead of your Strength bonus.",
            'special' => "",
        ), array(
            'name' => 'Alertness',
            'feat_type' => 'Skill Bonus',
            'prerequisites' => '',
            'effect' => 'Perception, Sense Motive',
            'description' => "You often notice things that others might miss.",
            'benefit' => "You get a +2 bonus on Perception and Sense Motive skill checks. If you have 10 or more ranks in one of these skills, the bonus increases to +4 for that skill.",
            'special' => "",
        ), array(
            'name' => 'Alignment Channel',
            'feat_type' => 'Magic',
            'prerequisites' => 'Ability to channel energy.',
            'effect' => '',
            'description' => "Choose chaos, evil, good, or law. You can channel divine energy to affect outsiders that possess this subtype.",
            'benefit' => "Instead of its normal effect, you can choose to have your ability to channel energy heal or harm outsiders of the chosen alignment subtype. You must make this choice each time you channel energy. If you choose to heal or harm creatures of the chosen alignment subtype, your channel energy has no effect on other creatures. The amount of damage healed or dealt and the DC to halve the damage is otherwise unchanged.",
            'special' => "You can gain this feat multiple times. Its effects do not stack. Each time you take this feat, it applies to a new alignment subtype. Whenever you channel energy, you must choose which type to effect.",
        ), array(
            'name' => 'Animal Affinity',
            'feat_type' => 'Skill Bonus',
            'prerequisites' => '',
            'effect' => 'Handle Animal, Ride',
            'description' => "You are skilled at working with animals and mounts.",
            'benefit' => "You get a +2 bonus on all Handle Animal and Ride skill checks. If you have 10 or more ranks in one of these skills, the bonus increases to +4 for that skill.",
            'special' => "",
        ), array(
            'name' => 'Arcane Armor Mastery',
            'feat_type' => 'Combat',
            'prerequisites' => 'Arcane Armor Training, Medium Armor Proficiency, caster level 7th.',
            'effect' => '',
            'description' => "You have mastered the ability to cast spells while wearing armor.",
            'benefit' => "As a swift action, reduce the arcane spell failure chance due to the armor you are wearing by 20% for any spells you cast this round. This bonus replaces, and does not stack with, the bonus granted by Arcane Armor Training.",
            'special' => "",
        ), array(
            'name' => 'Arcane Armor Training',
            'feat_type' => 'Combat',
            'prerequisites' => 'Light Armor Proficiency, caster level 3rd.',
            'effect' => '',
            'description' => "You have learned how to cast spells while wearing armor.",
            'benefit' => "As a swift action, reduce the arcane spell failure chance due to the armor you are wearing by 10% for any spells you cast this round.",
            'special' => "",
        ), array(
            'name' => 'Arcane Strike',
            'feat_type' => 'Combat',
            'prerequisites' => 'Ability to cast arcane spells.',
            'effect' => '',
            'description' => "You draw upon your arcane power to enhance your weapons with magical energy.",
            'benefit' => "As a swift action, you can imbue your weapons with a fraction of your power. For 1 round, your weapons deal +1 damage and are treated as magic for the purpose of overcoming damage reduction. For every five caster levels you possess, this bonus increases by +1, to a maximum of +5 at 20th level.",
            'special' => "",
        ), array(
            'name' => 'Armor Proficiency, Heavy',
            'feat_type' => 'General',
            'prerequisites' => 'Light Armor Proficiency, Medium Armor Proficiency.',
            'effect' => 'AC-penalty only for DEX and STR based skill checks',
            'description' => "You are skilled at wearing heavy armor.",
            'benefit' => "When you wear a type of armor with which you are proficient, the armor check penalty for that armor applies only to Dexterity- and Strength-based skill checks.",
            'special' => "Fighters and paladins automatically have Heavy Armor Proficiency as a bonus feat. They need not select it.",
        ), array(
            'name' => 'Armor Proficiency, Light',
            'feat_type' => 'General',
            'prerequisites' => '',
            'effect' => 'AC-penalty only for DEX and STR based skill checks',
            'description' => "You are skilled at wearing light armor.",
            'benefit' => "When you wear a type of armor with which you are proficient, the armor check penalty for that armor applies only to Dexterity- and Strength-based skill checks.",
            'special' => "All characters except monks, sorcerers, and wizards automatically have Light Armor Proficiency as a bonus feat. They need not select it.",
        ), array(
            'name' => 'Armor Proficiency, Medium',
            'feat_type' => 'General',
            'prerequisites' => '',
            'effect' => 'AC-penalty only for DEX and STR based skill checks',
            'description' => "You are skilled at wearing medium armor.",
            'benefit' => "When you wear a type of armor with which you are proficient, the armor check penalty for that armor applies only to Dexterity- and Strength-based skill checks.",
            'special' => " Barbarians, clerics, druids, fighters, paladins, and rangers automatically have Medium Armor Proficiency as a bonus feat. They need not select it.",
        ), array(
            'name' => 'Athletic',
            'feat_type' => 'Skill Bonus',
            'prerequisites' => '',
            'effect' => 'Climb, Swim',
            'description' => "You possess inherent physical prowess.",
            'benefit' => "You get a +2 bonus on Climb and Swim skill checks. If you have 10 or more ranks in one of these skills, the bonus increases to +4 for that skill.",
            'special' => "",
        ), array(
            'name' => 'Augment Summoning',
            'feat_type' => 'Magic',
            'prerequisites' => 'Spell Focus (conjuration)',
            'effect' => '',
            'description' => "Your summoned creatures are more powerful and robust.",
            'benefit' => "Each creature you conjure with any summon spell gains a +4 enhancement bonus to Strength and Constitution for the duration of the spell that summoned it.",
            'special' => "",
        ), array(
            'name' => 'Bleeding Critical',
            'feat_type' => 'Combat',
            'prerequisites' => 'Critical Focus, base attack bonus +11',
            'effect' => '',
            'description' => "Your critical hits cause opponents to bleed profusely.",
            'benefit' => "Whenever you score a critical hit with a slashing or piercing weapon, your opponent takes 2d6 points of bleed damage (see Conditions) each round on his turn, in addition to the damage dealt by the critical hit. Bleed damage can be stopped by a DC 15 Heal skill check or through any magical healing. The effects of this feat stack.",
            'special' => "You can only apply the effects of one critical feat to a given critical hit unless you possess Critical Mastery.",
        ), array(
            'name' => 'Blind-Fight',
            'feat_type' => 'Combat',
            'prerequisites' => '',
            'effect' => '',
            'description' => "You are skilled at attacking opponents that you cannot clearly perceive.",
            'benefit' => "In melee, every time you miss because of concealment (see Combat), you can reroll your miss chance percentile roll one time to see if you actually hit. An invisible attacker gets no advantages related to hitting you in melee. That is, you don't lose your Dexterity bonus to Armor Class, and the attacker doesn't get the usual +2 bonus for being invisible. The invisible attacker's bonuses do still apply for ranged attacks, however. You do not need to make Acrobatics skill checks to move at full speed while blinded.",
            'special' => "The Blind-Fight feat is of no use against a character who is the subject of a blink spell.",
        ), array(
            'name' => 'Blinding Critical',
            'feat_type' => 'Combat',
            'prerequisites' => 'Critical Focus, base attack bonus +15',
            'effect' => '',
            'description' => "Your critical hits blind your opponents.",
            'benefit' => "Whenever you score a critical hit, your opponent is permanently blinded. A successful Fortitude save reduces this to dazzled for 1d4 rounds. The DC of this Fortitude save is equal to 10 + your base attack bonus. This feat has no effect on creatures that do not rely on eyes for sight or creatures with more than two eyes (although multiple critical hits might cause blindness, at the GM's discretion). Blindness can be cured by heal, regeneration, remove blindness, or similar abilities.",
            'special' => "You can only apply the effects of one critical feat to a given critical hit unless you possess Critical Mastery.",
        ), array(
            'name' => 'Brew Potion',
            'feat_type' => 'Item Creation',
            'prerequisites' => 'Caster level 3rd',
            'effect' => '',
            'description' => "You can create magic potions.",
            'benefit' => "You can create a potion of any 3rd-level or lower spell that you know and that targets one or more creatures or objects. Brewing a potion takes 2 hours if its base price is 250 gp or less, otherwise brewing a potion takes 1 day for each 1,000 gp in its base price. When you create a potion, you set the caster level, which must be sufficient to cast the spell in question and no higher than your own level. To brew a potion, you must use up raw materials costing one half this base price. See the magic item creation rules in Magic Items for more information. When you create a potion, you make any choices that you would normally make when casting the spell. Whoever drinks the potion is the target of the spell.",
            'special' => "",
        ), array(
            'name' => 'Catch Off-Guard',
            'feat_type' => 'Combat',
            'prerequisites' => '',
            'effect' => '',
            'description' => "Foes are surprised by your skilled use of unorthodox and improvised weapons.",
            'benefit' => "You do not suffer any penalties for using an improvised melee weapon. Unarmed opponents are flat-footed against any attacks you make with an improvised melee weapon.",
            'special' => "",
        ), array(
            'name' => 'Channel Smite',
            'feat_type' => 'Combat',
            'prerequisites' => 'Channel energy class feature',
            'effect' => '',
            'description' => "You can channel your divine energy through a melee weapon you wield.",
            'benefit' => "Before you make a melee attack roll, you can choose to spend one use of your channel energy ability as a swift action. If you channel positive energy and you hit an undead creature, that creature takes an amount of additional damage equal to the damage dealt by your channel positive energy ability. If you channel negative energy and you hit a living creature, that creature takes an amount of additional damage equal to the damage dealt by your channel negative energy ability. Your target can make a Will save, as normal, to halve this additional damage. If your attack misses, the channel energy ability is still expended with no effect.",
            'special' => "",
        ), array(
            'name' => 'Cleave',
            'feat_type' => 'Combat',
            'prerequisites' => 'Str 13, Power Attack, base attack bonus +1',
            'effect' => '',
            'description' => "You can strike two adjacent foes with a single swing.",
            'benefit' => "As a standard action, you can make a single attack at your full base attack bonus against a foe within reach. If you hit, you deal damage normally and can make an additional attack (using your full base attack bonus) against a foe that is adjacent to the first and also within reach. You can only make one additional attack per round with this feat. When you use this feat, you take a –2 penalty to your Armor Class until your next turn.",
            'special' => "",
        ), array(
            'name' => 'Combat Casting',
            'feat_type' => 'Combat',
            'prerequisites' => '',
            'effect' => '',
            'description' => "You are adept at spellcasting when threatened or distracted.",
            'benefit' => "You get a +4 bonus on concentration checks made to cast a spell or use a spell-like ability when casting on the defensive or while grappled.",
            'special' => "",
        ), array(
            'name' => 'Combat Expertise',
            'feat_type' => 'Combat',
            'prerequisites' => 'Int 13',
            'effect' => '',
            'description' => "You can increase your defense at the expense of your accuracy.",
            'benefit' => "You can choose to take a –1 penalty on melee attack rolls and combat maneuver checks to gain a +1 dodge bonus to your Armor Class. When your base attack bonus reaches +4, and every +4 thereafter, the penalty increases by –1 and the dodge bonus increases by +1. You can only choose to use this feat when you declare that you are making an attack or a full-attack action with a melee weapon. The effects of this feat last until your next turn.",
            'special' => "",
        ), array(
            'name' => 'Combat Reflexes',
            'feat_type' => 'Combat',
            'prerequisites' => '',
            'effect' => '',
            'description' => "You can make additional attacks of opportunity.",
            'benefit' => "You may make a number of additional attacks of opportunity per round equal to your Dexterity bonus. With this feat, you may also make attacks of opportunity while flat-footed.",
            'special' => "The Combat Reflexes feat does not allow a rogue to use her opportunist ability more than once per round.",
        ), array(
            'name' => 'Command Undead',
            'feat_type' => 'Magic',
            'prerequisites' => 'Channel negative energy class feature',
            'effect' => '',
            'description' => "Using foul powers of necromancy, you can command undead creatures, making them into your servants.",
            'benefit' => "As a standard action, you can use one of your uses of channel negative energy to enslave undead within 30 feet. Undead receive a Will save to negate the effect. The DC for this Will save is equal to 10 + 1/2 your cleric level + your Charisma modifier. Undead that fail their saves fall under your control, obeying your commands to the best of their ability, as if under the effects of control undead. Intelligent undead receive a new saving throw each day to resist your command. You can control any number of undead, so long as their total Hit Dice do not exceed your cleric level. If you use channel energy in this way, it has no other effect (it does not heal or harm nearby creatures). If an undead creature is under the control of another creature, you must make an opposed Charisma check whenever your orders conflict.",
            'special' => "",
        ), array(
            'name' => 'Craft Magic Arms and Armor',
            'feat_type' => 'Item Creation',
            'prerequisites' => 'Caster level 5th',
            'effect' => '',
            'description' => "You can create magic armor, shields, and weapons.",
            'benefit' => "You can create magic weapons, armor, or shields. Enhancing a weapon, suit of armor, or shield takes 1 day for each 1,000 gp in the price of its magical features. To enhance a weapon, suit of armor, or shield, you must use up raw materials costing half of this total price. See the magic item creation rules in Magic Items for more information. The weapon, armor, or shield to be enhanced must be a masterwork item that you provide. Its cost is not included in the above cost. You can also mend a broken magic weapon, suit of armor, or shield if it is one that you could make. Doing so costs half the raw materials and half the time it would take to craft that item in the first place.",
            'special' => "",
        ), array(
            'name' => 'Craft Rod',
            'feat_type' => 'Item Creation',
            'prerequisites' => 'Caster level 9th',
            'effect' => '',
            'description' => "You can create magic rods.",
            'benefit' => "You can create magic rods. Crafting a rod takes 1 day for each 1,000 gp in its base price. To craft a rod, you must use up raw materials costing half of its base price. See the magic item creation rules in Magic Items for more information.",
            'special' => "",
        ), array(
            'name' => 'Craft Staff',
            'feat_type' => 'Item Creation',
            'prerequisites' => 'Caster level 11th',
            'effect' => '',
            'description' => "You can create magic staves.",
            'benefit' => "You can create any staff whose prerequisites you meet. Crafting a staff takes 1 day for each 1,000 gp in its base price. To craft a staff, you must use up raw materials costing half of its base price. A newly created staff has 10 charges. See the magic item creation rules in Magic Items for more information.",
            'special' => "",
        ), array(
            'name' => 'Craft Wand',
            'feat_type' => 'Item Creation',
            'prerequisites' => 'Caster level 5th',
            'effect' => '',
            'description' => "You can create magic staves.",
            'benefit' => "You can create a wand of any 4th-level or lower spell that you know. Crafting a wand takes 1 day for each 1,000 gp in its base price. To craft a wand, you must use up raw materials costing half of this base price. A newly created wand has 50 charges. See the magic item creation rules in Magic Items for more information.",
            'special' => "",
        ), array(
            'name' => 'Craft Wondrous Item',
            'feat_type' => 'Item Creation',
            'prerequisites' => 'Caster level 3rd',
            'effect' => '',
            'description' => "You can create wondrous items, a type of magic item.",
            'benefit' => "You can create a wide variety of magic wondrous items. Crafting a wondrous item takes 1 day for each 1,000 gp in its price. To create a wondrous item, you must use up raw materials costing half of its base price. See the magic item creation rules in Magic Items for more information. You can also mend a broken wondrous item if it is one that you could make. Doing so costs half the raw materials and half the time it would take to craft that item.",
            'special' => "",
        ), array(
            'name' => 'Critical Focus',
            'feat_type' => 'Combat',
            'prerequisites' => 'Base attack bonus +9.',
            'effect' => '',
            'description' => "You are trained in the art of causing pain.",
            'benefit' => "You receive a +4 circumstance bonus on attack rolls made to confirm critical hits.",
            'special' => "",
        ), array(
            'name' => 'Critical Mastery',
            'feat_type' => 'Combat',
            'prerequisites' => 'Critical Focus, any two critical feats, 14th-level fighter.',
            'effect' => '',
            'description' => "Your critical hits cause two additional effects.",
            'benefit' => "When you score a critical hit, you can apply the effects of two critical feats in addition to the damage dealt.",
            'special' => "",
        ), array(
            'name' => 'Dazzling Display',
            'feat_type' => 'Combat',
            'prerequisites' => 'Weapon Focus, proficiency with the selected weapon',
            'effect' => '',
            'description' => "Your skill with your favored weapon can frighten enemies.",
            'benefit' => "While wielding the weapon in which you have Weapon Focus, you can perform a bewildering show of prowess as a full-round action. Make an Intimidate check to demoralize all foes within 30 feet who can see your display.",
            'special' => "",
        ), array(
            'name' => 'Deadly Aim',
            'feat_type' => 'Combat',
            'prerequisites' => 'Dex 13, base attack bonus +1',
            'effect' => '',
            'description' => "You can make exceptionally deadly ranged attacks by pinpointing a foe's weak spot, at the expense of making the attack less likely to succeed.",
            'benefit' => "You can choose to take a –1 penalty on all ranged attack rolls to gain a +2 bonus on all ranged damage rolls. When your base attack bonus reaches +4, and every +4 thereafter, the penalty increases by –1 and the bonus to damage increases by +2. You must choose to use this feat before making an attack roll and its effects last until your next turn. The bonus damage does not apply to touch attacks or effects that do not deal hit point damage.",
            'special' => "",
        ), array(
            'name' => 'Deadly Stroke',
            'feat_type' => 'Combat',
            'prerequisites' => 'Dazzling Display, Greater Weapon Focus, Shatter Defenses, Weapon Focus, proficiency with the selected weapon, base attack bonus +11',
            'effect' => '',
            'description' => "With a well-placed strike, you can bring a swift and painful end to most foes.",
            'benefit' => "As a standard action, make a single attack with the weapon for which you have Greater Weapon Focus against a stunned or flat-footed opponent. If you hit, you deal double the normal damage and the target takes 1 point of Constitution bleed (see Conditions). The additional damage and bleed is not multiplied on a critical hit.",
            'special' => "",
        ), array(
            'name' => 'Deafening Critical',
            'feat_type' => 'Combat',
            'prerequisites' => 'Critical Focus, base attack bonus +13',
            'effect' => '',
            'description' => "Your critical hits cause enemies to lose their hearing.",
            'benefit' => "Whenever you score a critical hit against an opponent, the victim is permanently deafened. A successful Fortitude save reduces the deafness to 1 round. The DC of this Fortitude save is equal to 10 + your base attack bonus. This feat has no effect on deaf creatures. This deafness can be cured by heal, regeneration, remove deafness, or a similar ability.",
            'special' => "You can only apply the effects of one critical feat to a given critical hit unless you possess Critical Mastery.",
        ), array(
            'name' => 'Deceitful',
            'feat_type' => 'Skill Bonus',
            'prerequisites' => '',
            'effect' => 'Bluff, Disguise',
            'description' => "You are skilled at deceiving others, both with the spoken word and with physical disguises.",
            'benefit' => "You get a +2 bonus on all Bluff and Disguise skill checks. If you have 10 or more ranks in one of these skills, the bonus increases to +4 for that skill.",
            'special' => "",
        ), array(
            'name' => 'Defensive Combat Training',
            'feat_type' => 'General',
            'prerequisites' => '',
            'effect' => 'CMD gets HP in place of BAB',
            'description' => "You excel at defending yourself from all manner of combat maneuvers.",
            'benefit' => "You treat your total Hit Dice as your base attack bonus when calculating your Combat Maneuver Defense.",
            'special' => "",
        ), array(
            'name' => 'Deflect Arrows',
            'feat_type' => 'Combat',
            'prerequisites' => 'Dex 13, Improved Unarmed Strike',
            'effect' => '',
            'description' => "You can knock arrows and other projectiles off course, preventing them from hitting you.",
            'benefit' => "You must have at least one hand free (holding nothing) to use this feat. Once per round when you would normally be hit with an attack from a ranged weapon, you may deflect it so that you take no damage from it. You must be aware of the attack and not flat-footed. Attempting to deflect a ranged attack doesn't count as an action. Unusually massive ranged weapons (such as boulders or ballista bolts) and ranged attacks generated by natural attacks or spell effects can't be deflected.",
            'special' => "",
        ), array(
            'name' => 'Deft Hands',
            'feat_type' => 'Skill Bonus',
            'prerequisites' => '',
            'effect' => 'Disable Device, Sleight of Hand',
            'description' => "You have exceptional manual dexterity.",
            'benefit' => "You get a +2 bonus on Disable Device and Sleight of Hand skill checks. If you have 10 or more ranks in one of these skills, the bonus increases to +4 for that skill.",
            'special' => "",
        ), array(
            'name' => 'Diehard',
            'feat_type' => 'Combat',
            'prerequisites' => 'Endurance',
            'effect' => '',
            'description' => "You are especially hard to kill. Not only do your wounds automatically stabilize when grievously injured, but you can remain conscious and continue to act even at death's door.",
            'benefit' => "When your hit point total is below 0, but you are not dead, you automatically stabilize. You do not need to make a Constitution check each round to avoid losing additional hit points. You may choose to act as if you were disabled, rather than dying. You must make this decision as soon as you are reduced to negative hit points (even if it isn't your turn). If you do not choose to act as if you were disabled, you immediately fall unconscious. When using this feat, you are staggered. You can take a move action without further injuring yourself, but if you perform any standard action (or any other action deemed as strenuous, including some swift actions, such as casting a quickened spell) you take 1 point of damage after completing the act. If your negative hit points are equal to or greater than your Constitution score, you immediately die.",
            'special' => "",
        ), array(
            'name' => 'Disruptive',
            'feat_type' => 'Combat',
            'prerequisites' => '6th-level fighter',
            'effect' => '',
            'description' => "Your training makes it difficult for enemy spellcasters to safely cast spells near you.",
            'benefit' => "The DC to cast spells defensively increases by +4 for all enemies that are within your threatened area. This increase to casting spells defensively only applies if you are aware of the enemy's location and are capable of taking an attack of opportunity. If you can only take one attack of opportunity per round and have already used that attack, this increase does not apply.",
            'special' => "",
        ), array(
            'name' => 'Dodge',
            'feat_type' => 'General',
            'prerequisites' => 'Dex 13',
            'effect' => '+1 dodge',
            'description' => "Your training and reflexes allow you to react swiftly to avoid an opponents' attacks.",
            'benefit' => "You gain a +1 dodge bonus to your AC. A condition that makes you lose your Dex bonus to AC also makes you lose the benefits of this feat.",
            'special' => "",
        ), array(
            'name' => 'Double Slice',
            'feat_type' => 'Combat',
            'prerequisites' => 'Dex 15, Two-Weapon Fighting',
            'effect' => '',
            'description' => "Your off-hand weapon while dual-wielding strikes with greater power.",
            'benefit' => "Add your Strength bonus to damage rolls made with your off-hand weapon.",
            'special' => "",
        ), array(
            'name' => 'Elemental Channel',
            'feat_type' => 'Magic',
            'prerequisites' => 'Channel energy class feature',
            'effect' => '',
            'description' => "Choose one elemental subtype, such as air, earth, fire, or water. You can channel your divine energy to harm or heal outsiders that possess your chosen elemental subtype.",
            'benefit' => "Instead of its normal effect, you can choose to have your ability to channel energy heal or harm outsiders of your chosen elemental subtype. You must make this choice each time you channel energy. If you choose to heal or harm creatures of your elemental subtype, your channel energy has no affect on other creatures. The amount of damage healed or dealt and the DC to halve the damage is otherwise unchanged.",
            'special' => "You can gain this feat multiple times. Its effects do not stack. Each time you take this feat, it applies to a new elemental subtype.",
        ), array(
            'name' => 'Empower Spell',
            'feat_type' => 'Metamagic',
            'prerequisites' => '',
            'effect' => '',
            'description' => "You can increase the power of your spells, causing them to deal more damage.",
            'benefit' => "All variable, numeric effects of an empowered spell are increased by half, including bonuses to those dice rolls. Saving throws and opposed rolls are not affected, nor are spells without random variables. An empowered spell uses up a spell slot two levels higher than the spell’s actual level.",
            'special' => "",
        ), array(
            'name' => 'Endurance',
            'feat_type' => 'General',
            'prerequisites' => '',
            'effect' => '',
            'description' => "Harsh conditions or long exertions do not easily tire you.",
            'benefit' => "You gain a +4 bonus on the following checks and saves: Swim checks made to resist nonlethal damage from exhaustion; Constitution checks made to continue running; Constitution checks made to avoid nonlethal damage from a forced march; Constitution checks made to hold your breath; Constitution checks made to avoid nonlethal damage from starvation or thirst; Fortitude saves made to avoid nonlethal damage from hot or cold environments; and Fortitude saves made to resist damage from suffocation. You may sleep in light or medium armor without becoming fatigued.",
            'special' => "",
        ), array(
            'name' => 'Enlarge Spell',
            'feat_type' => 'Metamagic',
            'prerequisites' => '',
            'effect' => '',
            'description' => "You can increase the range of your spells.",
            'benefit' => "You can alter a spell with a range of close, medium, or long to increase its range by 100%. An enlarged spell with a range of close now has a range of 50 ft. + 5 ft./level, while medium-range spells have a range of 200 ft. + 20 ft./level and long-range spells have a range of 800 ft. + 80 ft./level. An enlarged spell uses up a spell slot one level higher than the spell's actual level. Spells whose ranges are not defined by distance, as well as spells whose ranges are not close, medium, or long, do not benefit from this feat.",
            'special' => "",
        ), array(
            'name' => 'Eschew Materials',
            'feat_type' => 'Combat',
            'prerequisites' => '',
            'effect' => '',
            'description' => "You can cast many spells without needing to utilize minor material components.",
            'benefit' => "You can cast any spell with a material component costing 1 gp or less without needing that component. The casting of the spell still provokes attacks of opportunity as normal. If the spell requires a material component that costs more than 1 gp, you must have the material component on hand to cast the spell, as normal.",
            'special' => "",
        ), array(
            'name' => 'Exhausting Critical',
            'feat_type' => 'Combat',
            'prerequisites' => 'Critical Focus, Tiring Critical, base attack bonus +15',
            'effect' => '',
            'description' => "Your critical hits cause opponents to become exhausted.",
            'benefit' => "When you score a critical hit on a foe, your target immediately becomes exhausted. This feat has no effect on exhausted creatures.",
            'special' => "You can only apply the effects of one critical feat to a given critical hit unless you possess the Critical Mastery feat.",
        ), array(
            'name' => 'Exotic Weapon Proficiency',
            'feat_type' => 'Combat',
            'prerequisites' => 'Base attack bonus +1',
            'effect' => '',
            'description' => "Choose one type of exotic weapon, such as the spiked chain or whip. You understand how to use that type of exotic weapon in combat, and can utilize any special tricks or qualities that exotic weapon might allow.",
            'benefit' => "You make attack rolls with the weapon normally.",
            'special' => "You can gain Exotic Weapon Proficiency multiple times. Each time you take the feat, it applies to a new type of exotic weapon. ",
        ), array(
            'name' => 'Extend Spell',
            'feat_type' => 'Metamagic',
            'prerequisites' => '',
            'effect' => '',
            'description' => "You can make your spells last twice as long.",
            'benefit' => "An extended spell lasts twice as long as normal. A spell with a duration of concentration, instantaneous, or permanent is not affected by this feat. An extended spell uses up a spell slot one level higher than the spell's actual level.",
            'special' => "",
        ), array(
            'name' => 'Extra Channel',
            'feat_type' => 'Combat',
            'prerequisites' => 'Channel energy class feature.',
            'effect' => '',
            'description' => "You can channel divine energy more often.",
            'benefit' => "You can channel energy two additional times per day.",
            'special' => "If a paladin with the ability to channel positive energy takes this feat, she can use lay on hands four additional times a day, but only to channel positive energy.",
        ), array(
            'name' => 'Extra Ki',
            'feat_type' => 'Combat',
            'prerequisites' => 'Ki pool class feature.',
            'effect' => '',
            'description' => "You can use your ki pool more times per day than most.",
            'benefit' => "Your ki pool increases by 2.",
            'special' => "You can gain Extra Ki multiple times. Its effects stack.",
        ), array(
            'name' => 'Extra Lay On Hands',
            'feat_type' => 'Combat',
            'prerequisites' => 'Lay on hands class feature.',
            'effect' => '',
            'description' => "You can use your lay on hands ability more often.",
            'benefit' => "You can use your lay on hands ability two additional times per day. ",
            'special' => "You can gain Extra Lay On Hands multiple times. Its effects stack.",
        ), array(
            'name' => 'Extra Mercy',
            'feat_type' => 'Combat',
            'prerequisites' => 'Lay on hands class feature, mercy class feature.',
            'effect' => '',
            'description' => "Your lay on hands ability adds an additional mercy.",
            'benefit' => "Select one additional mercy for which you qualify. When you use lay on hands to heal damage to one target, it also receives the additional effects of this mercy.",
            'special' => "You can gain this feat multiple times. Its effects do not stack. Each time you take this feat, select a new mercy. ",
        ), array(
            'name' => 'Extra Performance',
            'feat_type' => 'Combat',
            'prerequisites' => 'Bardic performance class feature.',
            'effect' => '',
            'description' => "You can use your bardic performance ability more often than normal.",
            'benefit' => "You can use bardic performance for 6 additional rounds per day.",
            'special' => "You can gain Extra Performance multiple times. Its effects stack.",
        ), array(
            'name' => 'Extra Rage',
            'feat_type' => 'Combat',
            'prerequisites' => 'Rage class feature.',
            'effect' => '',
            'description' => "You can use your rage ability more than normal.",
            'benefit' => "You can rage for 6 additional rounds per day.",
            'special' => "You can gain Extra Rage multiple times. Its effects stack.",
        ), array(
            'name' => 'Far Shot',
            'feat_type' => 'Combat',
            'prerequisites' => 'Point-Blank Shot.',
            'effect' => '',
            'description' => "You are more accurate at longer ranges.",
            'benefit' => "You only suffer a –1 penalty per full range increment between you and your target when using a ranged weapon.",
            'special' => "",
        ), array(
            'name' => 'Fleet',
            'feat_type' => 'General',
            'prerequisites' => '',
            'effect' => '+5 speed with light armor',
            'description' => "You are faster than most.",
            'benefit' => "While you are wearing light or no armor, your base speed increases by 5 feet. You lose the benefits of this feat if you carry a medium or heavy load.",
            'special' => "You can take this feat multiple times. The effects stack.",
        ), array(
            'name' => 'Forge Ring',
            'feat_type' => 'Item Creation',
            'prerequisites' => 'Caster level 7th.',
            'effect' => '',
            'description' => "You can create magic rings.",
            'benefit' => "You can create magic rings. Crafting a ring takes 1 day for each 1,000 gp in its base price. To craft a ring, you must use up raw materials costing half of the base price. See the magic item creation rules in Magic Items for more information. You can also mend a broken ring if it is one that you could make. Doing so costs half the raw materials and half the time it would take to forge that ring in the first place.",
            'special' => "",
        ), array(
            'name' => "Gorgon's Fist",
            'feat_type' => 'Combat',
            'prerequisites' => 'Improved Unarmed Strike, Scorpion Style, base attack bonus +6.',
            'effect' => '',
            'description' => "With one well-placed blow, you leave your target reeling.",
            'benefit' => "As a standard action, make a single unarmed melee attack against a foe whose speed is reduced (such as from Scorpion Style). If the attack hits, you deal damage normally and the target is staggered until the end of your next turn unless it makes a Fortitude saving throw (DC 10 + 1/2 your character level + your Wis modifier). This feat has no effect on targets that are staggered.",
            'special' => "",
        ), array(
            'name' => 'Great Cleave',
            'feat_type' => 'Combat',
            'prerequisites' => 'Str 13, Cleave, Power Attack, base attack bonus +4.',
            'effect' => '',
            'description' => "You can strike many adjacent foes with a single blow.",
            'benefit' => "As a standard action, you can make a single attack at your full base attack bonus against a foe within reach. If you hit, you deal damage normally and can make an additional attack (using your full base attack bonus) against a foe that is adjacent to the previous foe and also within reach. If you hit, you can continue to make attacks against foes adjacent to the previous foe, so long as they are within your reach. You cannot attack an individual foe more than once during this attack action. When you use this feat, you take a –2 penalty to your Armor Class until your next turn.",
            'special' => "",
        ), array(
            'name' => 'Great Fortitude',
            'feat_type' => 'Combat',
            'prerequisites' => '',
            'effect' => '',
            'description' => "You are resistant to poisons, diseases, and other maladies.",
            'benefit' => "You get a +2 bonus on all Fortitude saving throws.",
            'special' => "",
        ), array(
            'name' => 'Greater Bull Rush',
            'feat_type' => 'Combat',
            'prerequisites' => 'Improved Bull Rush, Power Attack, base attack bonus +6, Str 13.',
            'effect' => '',
            'description' => "Your bull rush attacks throw enemies off balance.",
            'benefit' => "You receive a +2 bonus on checks made to bull rush a foe. This bonus stacks with the bonus granted by Improved Bull Rush. Whenever you bull rush an opponent, his movement provokes attacks of opportunity from all of your allies (but not you).",
            'special' => "",
        ), array(
            'name' => 'Greater Disarm',
            'feat_type' => 'Combat',
            'prerequisites' => '',
            'effect' => '',
            'description' => "You can knock weapons far from an enemy's grasp.",
            'benefit' => "Combat Expertise, Improved Disarm, base attack bonus +6, Int 13",
            'special' => "You receive a +2 bonus on checks made to disarm a foe. This bonus stacks with the bonus granted by Improved Disarm. Whenever you successfully disarm an opponent, the weapon lands 15 feet away from its previous wielder, in a random direction.",
        ), array(
            'name' => 'Greater Feint',
            'feat_type' => 'Combat',
            'prerequisites' => 'Combat Expertise, Improved Feint, base attack bonus +6, Int 13.',
            'effect' => '',
            'description' => "You are skilled at making foes overreact to your attacks.",
            'benefit' => "Whenever you use feint to cause an opponent to lose his Dexterity bonus, he loses that bonus until the beginning of your next turn, in addition to losing his Dexterity bonus against your next attack.",
            'special' => "",
        ), array(
            'name' => 'Greater Grapple',
            'feat_type' => 'Combat',
            'prerequisites' => 'Improved Grapple, Improved Unarmed Strike, base attack bonus +6, Dex 13.',
            'effect' => '',
            'description' => "Maintaining a grapple is second nature to you.",
            'benefit' => "You receive a +2 bonus on checks made to grapple a foe. This bonus stacks with the bonus granted by Improved Grapple. Once you have grappled a creature, maintaining the grapple is a move action. This feat allows you to make two grapple checks each round (to move, harm, or pin your opponent), but you are not required to make two checks. You only need to succeed at one of these checks to maintain the grapple.",
            'special' => "",
        ), array(
            'name' => 'Greater Overrun',
            'feat_type' => 'Combat',
            'prerequisites' => '',
            'effect' => '',
            'description' => "Enemies must dive to avoid your dangerous move.",
            'benefit' => "Improved Overrun, Power Attack, base attack bonus +6, Str 13.",
            'special' => "You receive a +2 bonus on checks made to overrun a foe. This bonus stacks with the bonus granted by Improved Overrun. Whenever you overrun opponents, they provoke attacks of opportunity if they are knocked prone by your overrun.",
        ), array(
            'name' => 'Greater Penetrating Strike',
            'feat_type' => 'Combat',
            'prerequisites' => 'Penetrating Strike, Weapon Focus, 16th-level fighter.',
            'effect' => '',
            'description' => "Your attacks penetrate the defenses of most foes. ",
            'benefit' => "Your attacks with weapons selected with Weapon Focus ignore up to 10 points of damage reduction. This amount is reduced to 5 points for damage reduction without a type (such as DR 10/—).",
            'special' => "",
        ), array(
            'name' => 'Greater Shield Focus',
            'feat_type' => 'Combat',
            'prerequisites' => '',
            'effect' => '',
            'description' => "You are skilled at deflecting blows with your shield.",
            'benefit' => "Shield Focus, Shield Proficiency, base attack bonus +1, 8th-level fighter.",
            'special' => "Increase the AC bonus granted by any shield you are using by 1. This bonus stacks with the bonus granted by Shield Focus.",
        ), array(
            'name' => 'Greater Spell Focus',
            'feat_type' => 'Combat',
            'prerequisites' => 'Spell Focus.',
            'effect' => '',
            'description' => "Choose a school of magic to which you have already applied the Spell Focus feat. Any spells you cast of this school are very hard to resist.",
            'benefit' => "Add +1 to the Difficulty Class for all saving throws against spells from the school of magic you select. This bonus stacks with the bonus from Spell Focus.",
            'special' => "You can gain this feat multiple times. Its effects do not stack. Each time you take the feat, it applies to a new school to which you already have applied the Spell Focus feat.",
        ), array(
            'name' => 'Greater Spell Penetration',
            'feat_type' => 'Combat',
            'prerequisites' => 'Spell Penetration.',
            'effect' => '',
            'description' => "Your spells break through spell resistance much more easily than most.",
            'benefit' => "You get a +2 bonus on caster level checks (1d20 + caster level) made to overcome a creature's spell resistance. This bonus stacks with the one from Spell Penetration.",
            'special' => "",
        ), array(
            'name' => 'Greater Sunder',
            'feat_type' => 'Combat',
            'prerequisites' => 'Improved Sunder, Power Attack, base attack bonus +6, Str 13.',
            'effect' => '',
            'description' => "Your devastating strikes cleave through weapons and armor and into their wielders, damaging both item and wielder alike in a single terrific strike.",
            'benefit' => "You receive a +2 bonus on checks made to sunder an item. This bonus stacks with the bonus granted by Improved Sunder. Whenever you sunder to destroy a weapon, shield, or suit of armor, any excess damage is applied to the item's wielder. No damage is transferred if you decide to leave the item with 1 hit point.",
            'special' => "",
        ), array(
            'name' => 'Greater Trip',
            'feat_type' => 'Combat',
            'prerequisites' => 'Combat Expertise, Improved Trip, base attack bonus +6, Int 13.',
            'effect' => '',
            'description' => "You can make free attacks on foes that you knock down.",
            'benefit' => "You receive a +2 bonus on checks made to trip a foe. This bonus stacks with the bonus granted by Improved Trip. Whenever you successfully trip an opponent, that opponent provokes attacks of opportunity.",
            'special' => "",
        ), array(
            'name' => 'Greater Two-Weapon Fighting',
            'feat_type' => 'Combat',
            'prerequisites' => 'Dex 19, Improved Two-Weapon Fighting, Two-Weapon Fighting, base attack bonus +11.',
            'effect' => '',
            'description' => "You are incredibly skilled at fighting with two weapons at the same time.",
            'benefit' => " You get a third attack with your off-hand weapon, albeit at a –10 penalty.",
            'special' => "",
        ), array(
            'name' => 'Greater Vital Strike',
            'feat_type' => 'Combat',
            'prerequisites' => 'Improved Vital Strike, Vital Strike, base attack bonus +16.',
            'effect' => '',
            'description' => "You can make a single attack that deals incredible damage.",
            'benefit' => "When you use the attack action, you can make one attack at your highest base attack bonus that deals additional damage. Roll the weapon's damage dice for the attack four times and add the results together before adding bonuses from Strength, weapon abilities (such as flaming), precision based damage, and other damage bonuses. These extra weapon damage dice are not multiplied on a critical hit, but are added to the total.",
            'special' => "",
        ), array(
            'name' => 'Greater Weapon Focus',
            'feat_type' => 'Combat',
            'prerequisites' => 'Proficiency with selected weapon, Weapon Focus with selected weapon, base attack bonus +1, 8th-level fighter.',
            'effect' => '',
            'description' => "Choose one type of weapon (including unarmed strike or grapple) for which you have already selected Weapon Focus. You are a master at your chosen weapon.",
            'benefit' => "You gain a +1 bonus on attack rolls you make using the selected weapon. This bonus stacks with other bonuses on attack rolls, including those from Weapon Focus.",
            'special' => "You can gain Greater Weapon Focus multiple times. Its effects do not stack. Each time you take the feat, it applies to a new type of weapon.",
        ), array(
            'name' => 'Greater Weapon Specialization',
            'feat_type' => 'Combat',
            'prerequisites' => 'Proficiency with selected weapon, Greater Weapon Focus with selected weapon, Weapon Focus with selected weapon, Weapon Specialization with selected weapon, 12th-level fighter.',
            'effect' => '',
            'description' => "Choose one type of weapon (including unarmed strike or grapple) for which you possess the Weapon Specialization feat. Your attacks with the chosen weapon are more devastating than normal.",
            'benefit' => " You gain a +2 bonus on all damage rolls you make using the selected weapon. This bonus to damage stacks with other damage roll bonuses, including any you gain from Weapon Specialization.",
            'special' => "You can gain Greater Weapon Specialization multiple times. Its effects do not stack. Each time you take the feat, it applies to a new type of weapon.",
        ), array(
            'name' => 'Heighten Spell',
            'feat_type' => 'Metamagic',
            'prerequisites' => '',
            'effect' => '',
            'description' => "You can cast spells as if they were a higher level.",
            'benefit' => "A heightened spell has a higher spell level than normal (up to a maximum of 9th level). Unlike other metamagic feats, Heighten Spell actually increases the effective level of the spell that it modifies. All effects dependent on spell level (such as saving throw DCs and ability to penetrate a lesser globe of invulnerability) are calculated according to the heightened level. The heightened spell is as difficult to prepare and cast as a spell of its effective level. ",
            'special' => "",
        ), array(
            'name' => 'Improved Bull Rush',
            'feat_type' => 'Combat',
            'prerequisites' => 'Str 13, Power Attack, base attack bonus +1.',
            'effect' => '',
            'description' => "You are skilled at pushing your foes around.",
            'benefit' => "You do not provoke an attack of opportunity when performing a bull rush combat maneuver. In addition, you receive a +2 bonus on checks made to bull rush a foe. You also receive a +2 bonus to your Combat Maneuver Defense whenever an opponent tries to bull rush you.",
            'special' => "",
        ), array(
            'name' => 'Improved Channel',
            'feat_type' => 'Combat',
            'prerequisites' => 'Channel energy class feature.',
            'effect' => '',
            'description' => "Your channeled energy is harder to resist.",
            'benefit' => "Add 2 to the DC of saving throws made to resist the effects of your channel energy ability.",
            'special' => "",
        ), array(
            'name' => 'Improved Counterspell',
            'feat_type' => 'Combat',
            'prerequisites' => '',
            'effect' => '',
            'description' => "You are skilled at countering the spells of others using similar spells.",
            'benefit' => "When counterspelling, you may use a spell of the same school that is one or more spell levels higher than the target spell.",
            'special' => "",
        ), array(
            'name' => 'Improved Critical',
            'feat_type' => 'Combat',
            'prerequisites' => 'Proficient with weapon, base attack bonus +8.',
            'effect' => '',
            'description' => "Attacks made with your chosen weapon are quite deadly.",
            'benefit' => "When using the weapon you selected, your threat range is doubled.",
            'special' => "You can gain Improved Critical multiple times. The effects do not stack. Each time you take the feat, it applies to a new type of weapon. This effect doesn't stack with any other effect that expands the threat range of a weapon.",
        ), array(
            'name' => 'Improved Disarm',
            'feat_type' => 'Combat',
            'prerequisites' => 'Int 13, Combat Expertise.',
            'effect' => '',
            'description' => "You are skilled at knocking weapons from a foe's grasp.",
            'benefit' => "You do not provoke an attack of opportunity when performing a disarm combat maneuver. In addition, you receive a +2 bonus on checks made to disarm a foe. You also receive a +2 bonus to your Combat Maneuver Defense whenever an opponent tries to disarm you.",
            'special' => "",
        ), array(
            'name' => 'Improved Familiar',
            'feat_type' => 'Combat',
            'prerequisites' => 'Ability to acquire a new familiar, compatible alignment, sufficiently high level (see table "improved familiar").',
            'effect' => '',
            'description' => "This feat allows you to acquire a powerful familiar, but only when you could normally acquire a new familiar.",
            'benefit' => "When choosing a familiar, the creatures listed below are also available to you. You may choose a familiar with an alignment up to one step away on each alignment axis (lawful through chaotic, good through evil).",
            'special' => "",
        ), array(
            'name' => 'Improved Feint',
            'feat_type' => 'Combat',
            'prerequisites' => 'Int 13, Combat Expertise.',
            'effect' => '',
            'description' => "You are skilled at fooling your opponents in combat.",
            'benefit' => "You can make a Bluff check to feint in combat as a move action.",
            'special' => "",
        ), array(
            'name' => 'Improved Grapple',
            'feat_type' => 'Combat',
            'prerequisites' => 'Dex 13, Improved Unarmed Strike.',
            'effect' => '',
            'description' => "You are skilled at grappling opponents.",
            'benefit' => "You do not provoke an attack of opportunity when performing a grapple combat maneuver. In addition, you receive a +2 bonus on checks made to grapple a foe. You also receive a +2 bonus to your Combat Maneuver Defense whenever an opponent tries to grapple you.",
            'special' => "",
        ), array(
            'name' => 'Improved Great Fortitude',
            'feat_type' => 'Combat',
            'prerequisites' => 'Great Fortitude.',
            'effect' => '',
            'description' => "You can draw upon an inner reserve to resist diseases, poisons, and other grievous harm.",
            'benefit' => "Once per day, you may reroll a Fortitude save. You must decide to use this ability before the results are revealed. You must take the second roll, even if it is worse.",
            'special' => "",
        ), array(
            'name' => 'Improved Initiative',
            'feat_type' => 'General',
            'prerequisites' => '',
            'effect' => '+4 to initiative',
            'description' => "Your quick reflexes allow you to react rapidly to danger.",
            'benefit' => "You get a +4 bonus on initiative checks.",
            'special' => "",
        ), array(
            'name' => 'Improved Iron Will',
            'feat_type' => 'Combat',
            'prerequisites' => 'Iron Will.',
            'effect' => '',
            'description' => "Your clarity of thought allows you to resist mental attacks.",
            'benefit' => "Once per day, you may reroll a Will save. You must decide to use this ability before the results are revealed. You must take the second roll, even if it is worse.",
            'special' => "",
        ), array(
            'name' => 'Improved Lightning Reflexes',
            'feat_type' => 'Combat',
            'prerequisites' => 'Lightning Reflexes.',
            'effect' => '',
            'description' => "You have a knack for avoiding danger all around you.",
            'benefit' => "Once per day, you may reroll a Reflex save. You must decide to use this ability before the results are revealed. You must take the second roll, even if it is worse.",
            'special' => "",
        ), array(
            'name' => 'Improved Overrun',
            'feat_type' => 'Combat',
            'prerequisites' => 'Str 13, Power Attack, base attack bonus +1.',
            'effect' => '',
            'description' => "You are skilled at running down your foes.",
            'benefit' => "You do not provoke an attack of opportunity when performing an overrun combat maneuver. In addition, you receive a +2 bonus on checks made to overrrun a foe. You also receive a +2 bonus to your Combat Maneuver Defense whenever an opponent tries to overrun you. Targets of your overrun attempt may not chose to avoid you.",
            'special' => "",
        ), array(
            'name' => 'Improved Precise Shot',
            'feat_type' => 'Combat',
            'prerequisites' => 'Dex 19, Point-Blank Shot, Precise Shot, base attack bonus +11.',
            'effect' => '',
            'description' => "Your ranged attacks ignore anything but total concealment and cover.",
            'benefit' => "Your ranged attacks ignore the AC bonus granted to targets by anything less than total cover, and the miss chance granted to targets by anything less than total concealment. Total cover and total concealment provide their normal benefits against your ranged attacks.",
            'special' => "",
        ), array(
            'name' => 'Improved Shield Bash',
            'feat_type' => 'Combat',
            'prerequisites' => 'Shield Proficiency.',
            'effect' => '',
            'description' => "You can protect yourself with your shield, even if you use it to attack.",
            'benefit' => "When you perform a shield bash, you may still apply the shield's shield bonus to your AC.",
            'special' => "",
        ), array(
            'name' => 'Improved Sunder',
            'feat_type' => 'Combat',
            'prerequisites' => 'Str 13, Power Attack, base attack bonus +1.',
            'effect' => '',
            'description' => "You are skilled at damaging your foes' weapons and armor.",
            'benefit' => "You do not provoke an attack of opportunity when performing a sunder combat maneuver. In addition, you receive a +2 bonus on checks made to sunder an item. You also receive a +2 bonus to your Combat Maneuver Defense whenever an opponent tries to sunder your gear. ",
            'special' => "",
        ), array(
            'name' => 'Improved Trip',
            'feat_type' => 'Combat',
            'prerequisites' => 'Int 13, Combat Expertise.',
            'effect' => '',
            'description' => "You are skilled at sending your opponents to the ground.",
            'benefit' => "You do not provoke an attack of opportunity when performing a trip combat maneuver. In addition, you receive a +2 bonus on checks made to trip a foe. You also receive a +2 bonus to your Combat Maneuver Defense whenever an opponent tries to trip you. ",
            'special' => "",
        ), array(
            'name' => 'Improved Two-Weapon Fighting',
            'feat_type' => 'Combat',
            'prerequisites' => 'Dex 17, Two-Weapon Fighting, base attack bonus +6.',
            'effect' => '',
            'description' => "You are skilled at fighting with two weapons.",
            'benefit' => "In addition to the standard single extra attack you get with an off-hand weapon, you get a second attack with it, albeit at a –5 penalty.",
            'special' => "",
        ), array(
            'name' => 'Improved Unarmed Strike',
            'feat_type' => 'Combat',
            'prerequisites' => '',
            'effect' => '',
            'description' => "You are skilled at fighting while unarmed.",
            'benefit' => "You are considered to be armed even when unarmed—you do not provoke attacks of opportunity when you attack foes while unarmed. Your unarmed strikes can deal lethal or nonlethal damage, at your choice.",
            'special' => "",
        ), array(
            'name' => 'Improved Vital Strike',
            'feat_type' => 'Combat',
            'prerequisites' => 'Vital Strike, base attack bonus +11.',
            'effect' => '',
            'description' => "You can make a single attack that deals a large amount of damage.",
            'benefit' => "When you use the attack action, you can make one attack at your highest base attack bonus that deals additional damage. Roll the weapon's damage dice for the attack three times and add the results together before adding bonuses from Strength, weapon special abilities (such as flaming), precision based damage, and other damage bonuses. These extra weapon damage dice are not multiplied on a critical hit, but are added to the total.",
            'special' => "",
        ), array(
            'name' => 'Improvised Weapon Mastery',
            'feat_type' => 'Combat',
            'prerequisites' => 'Catch Off-Guard or Throw Anything, base attack bonus +8.',
            'effect' => '',
            'description' => "You can turn nearly any object into a deadly weapon, from a razor-sharp chair leg to a sack of flour.",
            'benefit' => "You do not suffer any penalties for using an improvised weapon. Increase the amount of damage dealt by the improvised weapon by one step (for example, 1d4 becomes 1d6) to a maximum of 1d8 (2d6 if the improvised weapon is two-handed). The improvised weapon has a critical threat range of 19–20, with a critical multiplier of ×2.",
            'special' => "",
        ), array(
            'name' => 'Intimidating Prowess',
            'feat_type' => 'Combat',
            'prerequisites' => '',
            'effect' => '',
            'description' => "Your physical might is intimidating to others.",
            'benefit' => "Add your Strength modifier to Intimidate skill checks in addition to your Charisma modifier.",
            'special' => "",
        ), array(
            'name' => 'Iron Will',
            'feat_type' => 'General',
            'prerequisites' => '',
            'effect' => '+2 on will saves',
            'description' => "You are more resistant to mental effects.",
            'benefit' => "You get a +2 bonus on all Will saving throws.",
            'special' => "",
        ), array(
            'name' => 'Leadership',
            'feat_type' => 'General',
            'prerequisites' => 'Character level 7th.',
            'effect' => '',
            'description' => "You attract followers to your cause and a companion to join you on your adventures.",
            'benefit' => "This feat enables you to attract a loyal cohort and a number of devoted subordinates who assist you. A cohort is generally an NPC with class levels, while followers are typically lower level NPCs. See Table: Leadership for what level of cohort and how many followers you can recruit.",
            'special' => "Leadership Modifiers: Several factors can affect your Leadership score, causing it to vary from the base score (character level + Cha modifier). Your reputation (from the point of view of the cohort or follower you are trying to attract) raises or lowers your Leadership score.",
        ), array(
            'name' => 'Lightning Reflexes',
            'feat_type' => 'General',
            'prerequisites' => '',
            'effect' => '+2 on reflex saving',
            'description' => "You have faster reflexes than normal.",
            'benefit' => "You get a +2 bonus on all Reflex saving throws.",
            'special' => "",
        ), array(
            'name' => 'Lightning Stance',
            'feat_type' => 'Combat',
            'prerequisites' => 'Dex 17, Dodge, Wind Stance, base attack bonus +11.',
            'effect' => '',
            'description' => "The speed at which you move makes it nearly impossible for opponents to strike you.",
            'benefit' => "If you take two actions to move or a withdraw action in a turn, you gain 50% concealment for 1 round.",
            'special' => "",
        ), array(
            'name' => 'Lunge',
            'feat_type' => 'Combat',
            'prerequisites' => 'Base attack bonus +6',
            'effect' => '',
            'description' => "You can strike foes that would normally be out of reach.",
            'benefit' => "You can increase the reach of your melee attacks by 5 feet until the end of your turn by taking a –2 penalty to your AC until your next turn. You must decide to use this ability before any attacks are made.",
            'special' => "",
        ), array(
            'name' => 'Magical Aptitude',
            'feat_type' => 'Skill Bonus',
            'prerequisites' => '',
            'effect' => 'Spellcraft, Use Magic Device',
            'description' => "You are skilled at spellcasting and using magic items.",
            'benefit' => "You get a +2 bonus on all Spellcraft checks and Use Magic Device checks. If you have 10 or more ranks in one of these skills, the bonus increases to +4 for that skill.",
            'special' => "",
        ), array(
            'name' => 'Manyshot',
            'feat_type' => 'Combat',
            'prerequisites' => 'Dex 17, Point-Blank Shot, Rapid Shot, base attack bonus +6.',
            'effect' => '',
            'description' => "You can fire multiple arrows at a single target.",
            'benefit' => "When making a full-attack action with a bow, your first attack fires two arrows. If the attack hits, both arrows hit. Apply precision-based damage (such as sneak attack) and critical hit damage only once for this attack. Damage bonuses from using a composite bow with a high Strength bonus apply to each arrow, as do other damage bonuses, such as a ranger's favored enemy bonus. Damage reduction and resistances apply separately to each arrow.",
            'special' => "",
        ), array(
            'name' => 'Martial Weapon Proficiency',
            'feat_type' => 'Combat',
            'prerequisites' => '',
            'effect' => '',
            'description' => "Choose a type of martial weapon. You understand how to use that type of martial weapon in combat.",
            'benefit' => "You make attack rolls with the selected weapon normally (without the non-proficient penalty).",
            'special' => "Barbarians, fighters, paladins, and rangers are proficient with all martial weapons. They need not select this feat. You can gain Martial Weapon Proficiency multiple times. Each time you take the feat, it applies to a new type of weapon. ",
        ), array(
            'name' => 'Master Craftsman',
            'feat_type' => 'General',
            'prerequisites' => '5 ranks in any Craft or Profession skill.',
            'effect' => '',
            'description' => "Your superior crafting skills allow you to create simple magic items.",
            'benefit' => "Choose one Craft or Profession skill in which you possess at least 5 ranks. You receive a +2 bonus on your chosen Craft or Profession skill. Ranks in your chosen skill count as your caster level for the purposes of qualifying for the Craft Magic Arms and Armor and Craft Wondrous Item feats. You can create magic items using these feats, substituting your ranks in the chosen skill for your total caster level. You must use the chosen skill for the check to create the item. The DC to create the item still increases for any necessary spell requirements (see the magic item creation rules in Magic Items). You cannot use this feat to create any spell-trigger or spell-activation item.",
            'special' => "",
        ), array(
            'name' => 'Maximize Spell',
            'feat_type' => 'Metamagic',
            'prerequisites' => '',
            'effect' => '',
            'description' => "Your spells have the maximum possible effect.",
            'benefit' => "All variable, numeric effects of a spell modified by this feat are maximized. Saving throws and opposed rolls are not affected, nor are spells without random variables. A maximized spell uses up a spell slot three levels higher than the spell's actual level. An empowered, maximized spell gains the separate benefits of each feat: the maximum result plus half the normally rolled result.",
            'special' => "",
        ), array(
            'name' => "Medusa's Wrath",
            'feat_type' => 'Combat',
            'prerequisites' => "Improved Unarmed Strike, Gorgon's Fist, Scorpion Style, base attack bonus +11.",
            'effect' => '',
            'description' => "You can take advantage of your opponent's confusion, delivering multiple blows.",
            'benefit' => "Whenever you use the full-attack action and make at least one unarmed strike, you can make two additional unarmed strikes at your highest base attack bonus. These bonus attacks must be made against a dazed, flat-footed, paralyzed, staggered, stunned, or unconscious foe.",
            'special' => "",
        ), array(
            'name' => 'Mobility',
            'feat_type' => 'Combat',
            'prerequisites' => 'Dex 13, Dodge.',
            'effect' => '',
            'description' => "You can easily move through a dangerous melee.",
            'benefit' => "You get a +4 dodge bonus to Armor Class against attacks of opportunity caused when you move out of or within a threatened area. A condition that makes you lose your Dexterity bonus to Armor Class (if any) also makes you lose dodge bonuses.",
            'special' => "Dodge bonuses stack with each other, unlike most types of bonuses.",
        ), array(
            'name' => 'Mounted Archery',
            'feat_type' => 'Combat',
            'prerequisites' => 'Ride 1 rank, Mounted Combat.',
            'effect' => '',
            'description' => "You are skilled at making ranged attacks while mounted.",
            'benefit' => "The penalty you take when using a ranged weapon while mounted is halved: –2 instead of –4 if your mount is taking a double move, and –4 instead of –8 if your mount is running.",
            'special' => "",
        ), array(
            'name' => 'Mounted Combat',
            'feat_type' => 'Combat',
            'prerequisites' => 'Ride 1 rank.',
            'effect' => '',
            'description' => "You are adept at guiding your mount through combat.",
            'benefit' => "Once per round when your mount is hit in combat, you may attempt a Ride check (as an immediate action) to negate the hit. The hit is negated if your Ride check result is greater than the opponent's attack roll.",
            'special' => "",
        ), array(
            'name' => 'Natural Spell',
            'feat_type' => 'Combat',
            'prerequisites' => 'Wis 13, wild shape class feature.',
            'effect' => '',
            'description' => "You can cast spells even while in a form that cannot normally cast spells.",
            'benefit' => "You can complete the verbal and somatic components of spells while using wild shape. You substitute various noises and gestures for the normal verbal and somatic components of a spell. You can also use any material components or focuses you possess, even if such items are melded within your current form. This feat does not permit the use of magic items while you are in a form that could not ordinarily use them, and you do not gain the ability to speak while using wild shape.",
            'special' => "",
        ), array(
            'name' => 'Nimble Moves',
            'feat_type' => 'Combat',
            'prerequisites' => 'Dex 13.',
            'effect' => '',
            'description' => "You can move across a single obstacle with ease.",
            'benefit' => "Whenever you move, you may move through 5 feet of difficult terrain each round as if it were normal terrain. This feat allows you to take a 5-foot step into difficult terrain.",
            'special' => "",
        ), array(
            'name' => 'Alertness',
            'feat_type' => 'Combat',
            'prerequisites' => '',
            'effect' => '',
            'description' => "",
            'benefit' => "",
            'special' => "",
        ), array(
            'name' => 'Alertness',
            'feat_type' => 'Combat',
            'prerequisites' => '',
            'effect' => '',
            'description' => "",
            'benefit' => "",
            'special' => "",
        ), array(
            'name' => 'Alertness',
            'feat_type' => 'Combat',
            'prerequisites' => '',
            'effect' => '',
            'description' => "",
            'benefit' => "",
            'special' => "",
        ), array(
            'name' => 'Alertness',
            'feat_type' => 'Combat',
            'prerequisites' => '',
            'effect' => '',
            'description' => "",
            'benefit' => "",
            'special' => "",
        ), array(
            'name' => 'Alertness',
            'feat_type' => 'Combat',
            'prerequisites' => '',
            'effect' => '',
            'description' => "",
            'benefit' => "",
            'special' => "",
        ), array(
            'name' => 'Alertness',
            'feat_type' => 'Combat',
            'prerequisites' => '',
            'effect' => '',
            'description' => "",
            'benefit' => "",
            'special' => "",
        ), array(
            'name' => 'Alertness',
            'feat_type' => 'Combat',
            'prerequisites' => '',
            'effect' => '',
            'description' => "",
            'benefit' => "",
            'special' => "",
        ), array(
            'name' => 'Alertness',
            'feat_type' => 'Combat',
            'prerequisites' => '',
            'effect' => '',
            'description' => "",
            'benefit' => "",
            'special' => "",
        ), array(
            'name' => 'Alertness',
            'feat_type' => 'Combat',
            'prerequisites' => '',
            'effect' => '',
            'description' => "",
            'benefit' => "",
            'special' => "",
        ), array(
            'name' => 'Alertness',
            'feat_type' => 'Combat',
            'prerequisites' => '',
            'effect' => '',
            'description' => "",
            'benefit' => "",
            'special' => "",
        ), array(
            'name' => 'Alertness',
            'feat_type' => 'Combat',
            'prerequisites' => '',
            'effect' => '',
            'description' => "",
            'benefit' => "",
            'special' => "",
        ), array(
            'name' => 'Alertness',
            'feat_type' => 'Combat',
            'prerequisites' => '',
            'effect' => '',
            'description' => "",
            'benefit' => "",
            'special' => "",
        ), array(
            'name' => 'Alertness',
            'feat_type' => 'Combat',
            'prerequisites' => '',
            'effect' => '',
            'description' => "",
            'benefit' => "",
            'special' => "",
        ), array(
            'name' => 'Alertness',
            'feat_type' => 'Combat',
            'prerequisites' => '',
            'effect' => '',
            'description' => "",
            'benefit' => "",
            'special' => "",
        ), array(
            'name' => 'Alertness',
            'feat_type' => 'Combat',
            'prerequisites' => '',
            'effect' => '',
            'description' => "",
            'benefit' => "",
            'special' => "",
        ), array(
            'name' => 'Alertness',
            'feat_type' => 'Combat',
            'prerequisites' => '',
            'effect' => '',
            'description' => "",
            'benefit' => "",
            'special' => "",
        ), array(
            'name' => 'Alertness',
            'feat_type' => 'Combat',
            'prerequisites' => '',
            'effect' => '',
            'description' => "",
            'benefit' => "",
            'special' => "",
        ), array(
            'name' => 'Alertness',
            'feat_type' => 'Combat',
            'prerequisites' => '',
            'effect' => '',
            'description' => "",
            'benefit' => "",
            'special' => "",
        ), array(
            'name' => 'Alertness',
            'feat_type' => 'Combat',
            'prerequisites' => '',
            'effect' => '',
            'description' => "",
            'benefit' => "",
            'special' => "",
        ), array(
            'name' => 'Alertness',
            'feat_type' => 'Combat',
            'prerequisites' => '',
            'effect' => '',
            'description' => "",
            'benefit' => "",
            'special' => "",
        ), array(
            'name' => 'Alertness',
            'feat_type' => 'Combat',
            'prerequisites' => '',
            'effect' => '',
            'description' => "",
            'benefit' => "",
            'special' => "",
        ), array(
            'name' => 'Alertness',
            'feat_type' => 'Combat',
            'prerequisites' => '',
            'effect' => '',
            'description' => "",
            'benefit' => "",
            'special' => "",
        ), array(
            'name' => 'Alertness',
            'feat_type' => 'Combat',
            'prerequisites' => '',
            'effect' => '',
            'description' => "",
            'benefit' => "",
            'special' => "",
        ), array(
            'name' => 'Alertness',
            'feat_type' => 'Combat',
            'prerequisites' => '',
            'effect' => '',
            'description' => "",
            'benefit' => "",
            'special' => "",
        ), array(
            'name' => 'Alertness',
            'feat_type' => 'Combat',
            'prerequisites' => '',
            'effect' => '',
            'description' => "",
            'benefit' => "",
            'special' => "",
        ), array(
            'name' => 'Alertness',
            'feat_type' => 'Combat',
            'prerequisites' => '',
            'effect' => '',
            'description' => "",
            'benefit' => "",
            'special' => "",
        ), array(
            'name' => 'Alertness',
            'feat_type' => 'Combat',
            'prerequisites' => '',
            'effect' => '',
            'description' => "",
            'benefit' => "",
            'special' => "",
        ), array(
            'name' => 'Alertness',
            'feat_type' => 'Combat',
            'prerequisites' => '',
            'effect' => '',
            'description' => "",
            'benefit' => "",
            'special' => "",
        ), array(
            'name' => 'Alertness',
            'feat_type' => 'Combat',
            'prerequisites' => '',
            'effect' => '',
            'description' => "",
            'benefit' => "",
            'special' => "",
        ), array(
            'name' => 'Alertness',
            'feat_type' => 'Combat',
            'prerequisites' => '',
            'effect' => '',
            'description' => "",
            'benefit' => "",
            'special' => "",
        ), array(
            'name' => 'Alertness',
            'feat_type' => 'Combat',
            'prerequisites' => '',
            'effect' => '',
            'description' => "",
            'benefit' => "",
            'special' => "",
        ), array(
            'name' => 'Alertness',
            'feat_type' => 'Combat',
            'prerequisites' => '',
            'effect' => '',
            'description' => "",
            'benefit' => "",
            'special' => "",
        ), array(
            'name' => 'Alertness',
            'feat_type' => 'Combat',
            'prerequisites' => '',
            'effect' => '',
            'description' => "",
            'benefit' => "",
            'special' => "",
        ), array(
            'name' => 'Alertness',
            'feat_type' => 'Combat',
            'prerequisites' => '',
            'effect' => '',
            'description' => "",
            'benefit' => "",
            'special' => "",
        ), array(
            'name' => 'Alertness',
            'feat_type' => 'Combat',
            'prerequisites' => '',
            'effect' => '',
            'description' => "",
            'benefit' => "",
            'special' => "",
        ), array(
            'name' => 'Alertness',
            'feat_type' => 'Combat',
            'prerequisites' => '',
            'effect' => '',
            'description' => "",
            'benefit' => "",
            'special' => "",
        ), array(
            'name' => 'Alertness',
            'feat_type' => 'Combat',
            'prerequisites' => '',
            'effect' => '',
            'description' => "",
            'benefit' => "",
            'special' => "",
        ), array(
            'name' => 'Alertness',
            'feat_type' => 'Combat',
            'prerequisites' => '',
            'effect' => '',
            'description' => "",
            'benefit' => "",
            'special' => "",
        ), array(
            'name' => 'Alertness',
            'feat_type' => 'Combat',
            'prerequisites' => '',
            'effect' => '',
            'description' => "",
            'benefit' => "",
            'special' => "",
        ), array(
            'name' => 'Alertness',
            'feat_type' => 'Combat',
            'prerequisites' => '',
            'effect' => '',
            'description' => "",
            'benefit' => "",
            'special' => "",
        ), array(
            'name' => 'Alertness',
            'feat_type' => 'Combat',
            'prerequisites' => '',
            'effect' => '',
            'description' => "",
            'benefit' => "",
            'special' => "",
        ), array(
            'name' => 'Alertness',
            'feat_type' => 'Combat',
            'prerequisites' => '',
            'effect' => '',
            'description' => "",
            'benefit' => "",
            'special' => "",
        ), array(
            'name' => 'Alertness',
            'feat_type' => 'Combat',
            'prerequisites' => '',
            'effect' => '',
            'description' => "",
            'benefit' => "",
            'special' => "",
        ), array(
            'name' => 'Alertness',
            'feat_type' => 'Combat',
            'prerequisites' => '',
            'effect' => '',
            'description' => "",
            'benefit' => "",
            'special' => "",
        ), array(
            'name' => 'Alertness',
            'feat_type' => 'Combat',
            'prerequisites' => '',
            'effect' => '',
            'description' => "",
            'benefit' => "",
            'special' => "",
        ), array(
            'name' => 'Alertness',
            'feat_type' => 'Combat',
            'prerequisites' => '',
            'effect' => '',
            'description' => "",
            'benefit' => "",
            'special' => "",
        ), array(
            'name' => 'Alertness',
            'feat_type' => 'Combat',
            'prerequisites' => '',
            'effect' => '',
            'description' => "",
            'benefit' => "",
            'special' => "",
        ), array(
            'name' => 'Alertness',
            'feat_type' => 'Combat',
            'prerequisites' => '',
            'effect' => '',
            'description' => "",
            'benefit' => "",
            'special' => "",
        ), array(
            'name' => 'Alertness',
            'feat_type' => 'Combat',
            'prerequisites' => '',
            'effect' => '',
            'description' => "",
            'benefit' => "",
            'special' => "",
        ), array(
            'name' => 'Alertness',
            'feat_type' => 'Combat',
            'prerequisites' => '',
            'effect' => '',
            'description' => "",
            'benefit' => "",
            'special' => "",
        ), array(
            'name' => 'Alertness',
            'feat_type' => 'Combat',
            'prerequisites' => '',
            'effect' => '',
            'description' => "",
            'benefit' => "",
            'special' => "",
        ), array(
            'name' => 'Alertness',
            'feat_type' => 'Combat',
            'prerequisites' => '',
            'effect' => '',
            'description' => "",
            'benefit' => "",
            'special' => "",
        ), array(
            'name' => 'Alertness',
            'feat_type' => 'Combat',
            'prerequisites' => '',
            'effect' => '',
            'description' => "",
            'benefit' => "",
            'special' => "",
        ), array(
            'name' => 'Alertness',
            'feat_type' => 'Combat',
            'prerequisites' => '',
            'effect' => '',
            'description' => "",
            'benefit' => "",
            'special' => "",
        ), array(
            'name' => 'Alertness',
            'feat_type' => 'Combat',
            'prerequisites' => '',
            'effect' => '',
            'description' => "",
            'benefit' => "",
            'special' => "",
        ), array(
            'name' => 'Alertness',
            'feat_type' => 'Combat',
            'prerequisites' => '',
            'effect' => '',
            'description' => "",
            'benefit' => "",
            'special' => "",
        ), array(
            'name' => 'Alertness',
            'feat_type' => 'Combat',
            'prerequisites' => '',
            'effect' => '',
            'description' => "",
            'benefit' => "",
            'special' => "",
        ), array(
            'name' => 'Alertness',
            'feat_type' => 'Combat',
            'prerequisites' => '',
            'effect' => '',
            'description' => "",
            'benefit' => "",
            'special' => "",
        ), array(
            'name' => 'Alertness',
            'feat_type' => 'Combat',
            'prerequisites' => '',
            'effect' => '',
            'description' => "",
            'benefit' => "",
            'special' => "",
        ), array(
            'name' => 'Alertness',
            'feat_type' => 'Combat',
            'prerequisites' => '',
            'effect' => '',
            'description' => "",
            'benefit' => "",
            'special' => "",
        ), array(
            'name' => 'Alertness',
            'feat_type' => 'Combat',
            'prerequisites' => '',
            'effect' => '',
            'description' => "",
            'benefit' => "",
            'special' => "",
        ), array(
            'name' => 'Alertness',
            'feat_type' => 'Combat',
            'prerequisites' => '',
            'effect' => '',
            'description' => "",
            'benefit' => "",
            'special' => "",
        ), array(
            'name' => 'Alertness',
            'feat_type' => 'Combat',
            'prerequisites' => '',
            'effect' => '',
            'description' => "",
            'benefit' => "",
            'special' => "",
        ), array(
            'name' => 'Alertness',
            'feat_type' => 'Combat',
            'prerequisites' => '',
            'effect' => '',
            'description' => "",
            'benefit' => "",
            'special' => "",
        ), array(
            'name' => 'Alertness',
            'feat_type' => 'Combat',
            'prerequisites' => '',
            'effect' => '',
            'description' => "",
            'benefit' => "",
            'special' => "",
        ), array(
            'name' => 'Alertness',
            'feat_type' => 'Combat',
            'prerequisites' => '',
            'effect' => '',
            'description' => "",
            'benefit' => "",
            'special' => "",
        ), array(
            'name' => 'Alertness',
            'feat_type' => 'Combat',
            'prerequisites' => '',
            'effect' => '',
            'description' => "",
            'benefit' => "",
            'special' => "",
        ), array(
            'name' => 'Alertness',
            'feat_type' => 'Combat',
            'prerequisites' => '',
            'effect' => '',
            'description' => "",
            'benefit' => "",
            'special' => "",
        ), array(
            'name' => 'Alertness',
            'feat_type' => 'Combat',
            'prerequisites' => '',
            'effect' => '',
            'description' => "",
            'benefit' => "",
            'special' => "",
        ), array(
            'name' => 'Alertness',
            'feat_type' => 'Combat',
            'prerequisites' => '',
            'effect' => '',
            'description' => "",
            'benefit' => "",
            'special' => "",
        ), array(
            'name' => 'Alertness',
            'feat_type' => 'Combat',
            'prerequisites' => '',
            'effect' => '',
            'description' => "",
            'benefit' => "",
            'special' => "",
        ), array(
            'name' => 'Alertness',
            'feat_type' => 'Combat',
            'prerequisites' => '',
            'effect' => '',
            'description' => "",
            'benefit' => "",
            'special' => "",
        ), array(
            'name' => 'Alertness',
            'feat_type' => 'Combat',
            'prerequisites' => '',
            'effect' => '',
            'description' => "",
            'benefit' => "",
            'special' => "",
        ), array(
            'name' => 'Alertness',
            'feat_type' => 'Combat',
            'prerequisites' => '',
            'effect' => '',
            'description' => "",
            'benefit' => "",
            'special' => "",
        ), array(
            'name' => 'Alertness',
            'feat_type' => 'Combat',
            'prerequisites' => '',
            'effect' => '',
            'description' => "",
            'benefit' => "",
            'special' => "",
        ), array(
            'name' => 'Alertness',
            'feat_type' => 'Combat',
            'prerequisites' => '',
            'effect' => '',
            'description' => "",
            'benefit' => "",
            'special' => "",
        ), array(
            'name' => 'Alertness',
            'feat_type' => 'Combat',
            'prerequisites' => '',
            'effect' => '',
            'description' => "",
            'benefit' => "",
            'special' => "",
        ), array(
            'name' => 'Alertness',
            'feat_type' => 'Combat',
            'prerequisites' => '',
            'effect' => '',
            'description' => "",
            'benefit' => "",
            'special' => "",
        ), array(
            'name' => 'Alertness',
            'feat_type' => 'Combat',
            'prerequisites' => '',
            'effect' => '',
            'description' => "",
            'benefit' => "",
            'special' => "",
        ), array(
            'name' => 'Alertness',
            'feat_type' => 'Combat',
            'prerequisites' => '',
            'effect' => '',
            'description' => "",
            'benefit' => "",
            'special' => "",
        ), array(
            'name' => 'Alertness',
            'feat_type' => 'Combat',
            'prerequisites' => '',
            'effect' => '',
            'description' => "",
            'benefit' => "",
            'special' => "",
        ), array(
            'name' => 'Alertness',
            'feat_type' => 'Combat',
            'prerequisites' => '',
            'effect' => '',
            'description' => "",
            'benefit' => "",
            'special' => "",
        ), array(
            'name' => 'Alertness',
            'feat_type' => 'Combat',
            'prerequisites' => '',
            'effect' => '',
            'description' => "",
            'benefit' => "",
            'special' => "",
        )));
	}


	/**
	 * Reverse the migrations.
	 *
	 * @return void
	 */
	public function down()
	{
		Schema::drop('feats');
	}

}
